### ISSUE TITLE
Change the contstraints in the SDK videochat webrtc.jar

### ISSUE THREAD

**Issue by Loborro** [QuickBlox/q-municate-android#100]
How can i change the contstraints in the SDK videochat webrtc.jar, to make it customizable.

**Comment by tatanka987** [comment]
hello @Loborro, please see [our webRTC sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc) to look how to add settings to your project.
[There](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/SettingsUtil.java) class for processing settings.
[There](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-videochat-webrtc/src/main/res/xml/preferences.xml) preferences.xml.

**Comment by Loborro** [comment]
I was triying to change the constrains in "quickblox-android-sdk-videochat-webrtc-2.2.4.jar" unsuccessfully, i need to customize the app for low bandwith,i can find the "settingsutil.java" file in the source code of qmunicate to android. I can do the change this settings from another file to the source code?? or exist a way to modify the class "QBMediaStreamManager" in the file .jar??

**Comment by Loborro** [comment]
There is some way that i can configure the metod getUserMedia() directly??

**Comment by tatanka987** [comment]
you can use SettingsUtil.java for configure media settings, but before start call need init this settings

**Comment by RomanPronin** [comment]
Long time inactivity.
