### ISSUE TITLE
crashed after updating 2.4 to 2.6.1 on voice or video call

### ISSUE THREAD

**Issue by CRUDTechnolgoy** [QuickBlox/q-municate-android#102]
#
                                                           # Fatal error in ../../talk/app/webrtc/java/jni/classreferenceholder.cc, line 132
                                                           # Check failed: !jni->ExceptionCheck()
                                                           # error during FindClass: org/webrtc/VideoCapturerAndroid$NativeObserver
                                                           #

**Comment by tatanka987** [comment]
hello @CRUDTechnolgoy, additional you need update .jni libs in your project, for it move [this files](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc/src/main/jniLibs) to directory "jniLibs" in your project

**Comment by AustrianDudes** [comment]
I am experiencing the same error after updating from 2.6 to 2.6.1, but I am building my project using the provided .aar. Shouldn't this include the proper .jni libs?

    compile 'com.quickblox:quickblox-android-sdk-core:2.6.1@aar'
    compile("com.quickblox:quickblox-android-sdk-chat:2.6.1@aar") {
        transitive = true
    }
    compile 'com.quickblox:quickblox-android-sdk-videochat-webrtc:2.6.1@aar'

**Comment by CRUDTechnolgoy** [comment]
yas i have done it. thanks for your support.

**Comment by AustrianDudes** [comment]
I have created a seperate ticket, as the creator of this ticket has closed it https://github.com/QuickBlox/q-municate-android/issues/133
