### ISSUE TITLE
Adding someone through code

### ISSUE THREAD

**Issue by TomOerlemans** [QuickBlox/q-municate-android#104]
Hi,

For the past couple of days I've been trying to build some code to add new users with. I have been going through classes such as EmailHelper.java, ImportFriendsHelper.java, QBFriendListHelper.java and QBImportFriendsCommand.java. However, I haven't had any luck in getting this done, most of the code I understand is all about local operations. Anyone care to give me some pointers in the right direction?

Just to clarify, what I'd like to do, I'm trying to write some code which let's me:
1. Retrieve a list of user's from the server
2. Based on some criteria select one of these users
3. Add this user to the current user's friend list

Any help is much appreciated.

**Comment by tatanka987** [comment]
hello @TombaNL , on GlobalSearchFragment starts loading users by full name (code [there](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_app/src/main/java/com/quickblox/q_municate/ui/fragments/search/GlobalSearchFragment.java#L252), code of command for loading users [there](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_core/src/main/java/com/quickblox/q_municate_core/qb/commands/QBFindUsersCommand.java)), after getting list of users you can add they to own contact list

**Comment by RomanPronin** [comment]
Long time inactivity.
