### ISSUE TITLE
How Do I search Using Custom Data

### ISSUE THREAD

**Issue by harssh-shah** [QuickBlox/q-municate-android#125]
Hi,

I added Custom data to User by using "setJsonValue()" in Utils.java

I am able to see the data under the User data:
![image](https://cloud.githubusercontent.com/assets/6176002/18715538/55c8fd76-8037-11e6-8320-bae10a1c1bc6.png)

However, I need to search user using this Custom Data Like Profession or Pin, Is there a way I can achieve that?

**Comment by RomanPronin** [comment]
Hi @harssh-shah, for example you can add tag with name Profession or Pin, and get user by tag.

**Comment by harssh-shah** [comment]
@RomanPronin, Did the same added tag to users, Just need to know how can I search users by tags.
I know that it searches by full name now, where do I find that and change it to search by tags?

**Comment by RomanPronin** [comment]
Just use QBUsers.getUsersByTags, here is [link](http://quickblox.com/developers/SimpleSample-users-android#Retrieve_Users_by_tags)
