### ISSUE TITLE
Having login twitter digits and new features

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-android#130]
Hello everyone I downloaded the master version of q-be communicated and I'm looking at the code.
I note that this version does not have the logni via twitter digits and other features that between requests is said to have been implemented.

For all I have to use another branch? Which?

Thank you

**Comment by tatanka987** [comment]
Hello, yes, you can use "develop" branch, this branch contains code of app from Play Marker

**Comment by EminDemiri** [comment]
Thanks, Great seems to be everything.
I am seeing that there are many more parameters to be set, could you give me a hand in the initial configuration?

**Comment by tatanka987** [comment]
hello @EminDemiri, we added only three new parameters to buid.gradle file: 
prodTwittedDigitsApiKey=\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"
prodTwitterDigitsConsumerKey=\"xxxxxxxxxxxxxxxxxxxxxxxxxx\"
prodTwitterDigitsConsumerSecret=\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"

**prodTwitterDigitsConsumerKey** and **prodTwitterDigitsConsumerSecret** you can get from Fabric Dashboard https://fabric.io/dashboard in section Digits (before it you must be registered there and to have app) for your app (see my [screenshot](https://gyazo.com/06dae5045bcf1f00ceb6ccd1a8cefb9e))

**prodTwittedDigitsApiKey**  you can generate by [link ](https://fabric.io/kits/android/digits/install), for it press "I already have a Twitter application" ([my screenshot](https://gyazo.com/9ea1afc8c735e45f8861179d1d9372ba)), then paste your CONSUMER KEY (API KEY) and CONSUMER SECRET (API SECRET) to appropriate fields ([my screenshot](https://gyazo.com/92dbf5c581cd8c5f2ad157acd23204a0)) and press "Submit". After that you will get your Api key in xml above ([my screenshot](https://gyazo.com/94b526974d76a10f2435b81f35c4cc71))

**Comment by EminDemiri** [comment]
I have already operated the Web version of Q-Municate, I can use the same apikey?

maybe if you want to see: www.talkme.online

**Comment by tatanka987** [comment]
We published updated Q-municate version to **master** branch and updated [documentation](http://quickblox.com/developers/Q-municate#Q-municate_Android) by running Q-municate with your own credentials. Additional we pushed  stub file gradle.properties for simplify configure app. Please look documentation, check your project and try again.

**Comment by EminDemiri** [comment]
I thank you, you've been very helpful.
This weekend I will try to create a new project, if I have any problem surely you riverrò to seek :P 
Thanks for now

**Comment by EminDemiri** [comment]
I just finished compiling the new version 2.1.

I configured the gradle.properties file with all richeisti data.

I'm trying to connect / register via twitter digits mo I have problems:

I get a text message with the activation code, the app automatically takes the code and valid returning to home and telling me to wait.

after a few seconds you will see a Toast saying:
"Blob does not exist"

What could be the problem?

It states that the digist twitter codes work because I use them in the web version of q-municate.

**Comment by Odili9876** [comment]
It is very frustrating to get the fabric credentials. I logged in to my fabric dashboard but i did not a place to generate the credential.If possible make a video tutorial.Thanks

**Comment by Odili9876** [comment]
It is frustrating getting the digits credentials.I logged in to my fabric dashboard but i did not see a place to generate the keys.If possible make a video tutorial.thanks

**Comment by tatanka987** [comment]
hello @Odili9876 for getting Twitter Digits credentials you can use Fabric  [plugin](https://fabric.io/downloads/android-studio) for Android Studio. After installation this plugin you can create blank project in Android Studio, then need run this plugin and it automatically will add needed credentials to your project. You can move this credentials to your main project. 

P.S. If you have other questions, please create new issue.
