### ISSUE TITLE
Unable to search users through Tags

### ISSUE THREAD

**Issue by harssh-shah** [QuickBlox/q-municate-android#131]
Hi,

I am trying to search users through tags where I am using "getUsersByTags" method.

I added this in the "QBFindUsersByCommand.java" where I replaced "getUsersByFullName" by "getUsersByTags".

Now, whenever I search I see the request being sent: 
![tags_request](https://cloud.githubusercontent.com/assets/6176002/19238512/7d72c946-8f1f-11e6-8dfa-dc9f82b5053d.JPG)

However, the response shows no users, I.e the response is blank:
![tags_response](https://cloud.githubusercontent.com/assets/6176002/19238451/39446784-8f1f-11e6-91ce-b7484d0437ff.JPG)
Why is the response blank?
Also when I replace the method to search by full name again, it works.

What am I missing here?

**Comment by RomanPronin** [comment]
As I see, Response with Status 404 is NOT related with Request GET byTags. So, if you attach correct logs, we can help you.

**Comment by harssh-shah** [comment]
Hi,

Here is the log, can you check this and let me know if there is anything else you need?


10-12 21:17:59.886 21416-21416/com.quickblox.q_municate D/QBService: service started with resultAction=find_search_action
10-12 21:17:59.896 21416-30751/com.quickblox.q_municate D/QBASDK: =========================================================
                                                                  === REQUEST ==== 091b8159-9f19-47ce-8d02-f6c1d210904a ===
                                                                  REQUEST
                                                                      GET https://api.quickblox.com/users/by_tags.json
                                                                  HEADERS
                                                                      QuickBlox-REST-API-Version=0.1.1
                                                                      QB-SDK=Android 2.4
                                                                      QB-Token=91ce92dfd7c6adea3cf128498cf729bd8700b198
                                                                  PARAMETERS
                                                                      per_page=20
                                                                      tags=newtag
                                                                  INLINE
                                                                      GET https://api.quickblox.com/users/by_tags.json?per_page=20&tags=newtag
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate D/QBASDK: *********************************************************
                                                                  *** RESPONSE *** 091b8159-9f19-47ce-8d02-f6c1d210904a ***
                                                                  STATUS : 404 
                                                                  HEADERS
                                                                      Access-Control-Allow-Origin=*
                                                                      Cache-Control=no-cache
                                                                      Connection=keep-alive
                                                                      Content-Length=1
                                                                      Content-Type=application/json; charset=utf-8
                                                                      Date=Wed, 12 Oct 2016 15:48:06 GMT
                                                                      QB-Token-ExpirationDate=2016-10-12 17:36:26 UTC
                                                                      QuickBlox-REST-API-Version=0.1.1
                                                                      Server=openresty/1.9.15.1
                                                                      Status=404 Not Found
                                                                      X-Rack-Cache=miss
                                                                      X-Request-Id=2e8ed5c35f18334524855136d335cab2
                                                                      X-Runtime=0.258041
                                                                      X-UA-Compatible=IE=Edge,chrome=1
                                                                  BODY
                                                                      ' '
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err: com.quickblox.core.exception.QBResponseException: Entity you are looking for was not found.
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:78)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.core.query.Query.perform(Query.java:252)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.users.QBUsers.getUsersByTags(QBUsers.java:1398)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.q_municate_core.qb.commands.QBFindUsersCommand.perform(QBFindUsersCommand.java:50)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.q_municate_core.core.command.ServiceCommand.execute(ServiceCommand.java:27)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.q_municate_core.service.QBService$1.run(QBService.java:596)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at java.lang.Thread.run(Thread.java:841)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err: com.quickblox.core.exception.QBResponseException: Entity you are looking for was not found.
10-12 21:18:02.366 21416-21416/com.quickblox.q_municate D/STEPS: executing find_users_fail_action
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:78)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.core.query.Query.perform(Query.java:252)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.users.QBUsers.getUsersByTags(QBUsers.java:1398)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.q_municate_core.qb.commands.QBFindUsersCommand.perform(QBFindUsersCommand.java:50)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.q_municate_core.core.command.ServiceCommand.execute(ServiceCommand.java:27)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at com.quickblox.q_municate_core.service.QBService$1.run(QBService.java:596)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate W/System.err:     at java.lang.Thread.run(Thread.java:841)
10-12 21:18:02.366 21416-30751/com.quickblox.q_municate D/Utils: error =Entity you are looking for was not found.
10-12 21:18:02.476 21416-21416/com.quickblox.q_municate I/Choreographer: Skipped 77 frames!  The application may be doing too much work on its main thread.
10-12 21:18:03.866 21416-21574/com.quickblox.q_municate D/SMACK: SENT (0): <presence id='rEoUg-27'></presence>
10-12 21:18:03.916 21416-21416/com.quickblox.q_municate I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
10-12 21:18:04.656 18610-18631/? D/audio_hw_primary: found out /dev/snd/pcmC0D0p
10-12 21:18:04.656 18610-18631/? W/audio_hw_primary: out_write() limiting sleep time 69659 to 46439
10-12 21:18:04.676 21416-21416/com.quickblox.q_municate I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
10-12 21:18:04.706 18610-18631/? W/audio_hw_primary: out_write() limiting sleep time 55759 to 46439
10-12 21:18:04.766 19149-19149/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-Service: startService called with arg: notification
10-12 21:18:04.766 19149-19149/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-Service: New Notification has been observed, informing frontend now
10-12 21:18:04.766 19149-19149/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-Application: in sendHttpRequest, request to send to (fqdn): http://10.0.2.2:2861/notification
                                                                                                     data: {"content":"Choose input method*bst*English (US) - Android Keyboard (AOSP)","id":"17040512","pkg":"android","tickerText":"android"}
10-12 21:18:04.766 18945-18945/system_process D/NotificationService: In writeNotificationInfo: pkgName android
10-12 21:18:04.796 21416-21416/com.quickblox.q_municate I/Choreographer: Skipped 117 frames!  The application may be doing too much work on its main thread.
10-12 21:18:04.886 22035-22149/com.facebook.katana D/dalvikvm: GC_FOR_ALLOC freed 1160K, 18% free 5669K/6864K, paused 121ms, total 121ms
10-12 21:18:04.916 18945-18958/system_process I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
10-12 21:18:04.956 21416-21575/com.quickblox.q_municate D/SMACK: RCV (0): <presence xmlns="jabber:client" to="18258870-45464@chat.quickblox.com" id="rEoUg-27" from="18258870-45464@chat.quickblox.com/c95a420bbc2ddb7e"/>
10-12 21:18:06.236 19134-20394/com.bluestacks.bstfolder D/dalvikvm: GC_FOR_ALLOC freed 729K, 29% free 2753K/3832K, paused 16ms, total 17ms

**Comment by RomanPronin** [comment]
First of all check, that you have users with your tag "newtag", cause it is looks like you don't have.

**Comment by RomanPronin** [comment]
Long time inactivity.
