### ISSUE TITLE
Crash after updating from 2.6 to 2.6.1 on voice or video call 

### ISSUE THREAD

**Issue by AustrianDudes** [QuickBlox/q-municate-android#133]
Hi,
I have created this seperate ticket, as the original ticket has been closed by the creator (https://github.com/QuickBlox/q-municate-android/issues/102). I am experiencing following error on a voice or video call:

```
# 
# Fatal error in ../../talk/app/webrtc/java/jni/classreferenceholder.cc, line 132
# Check failed: !jni->ExceptionCheck()
# error during FindClass: org/webrtc/VideoCapturerAndroid$NativeObserver
#
```

The error occurs after updating from 2.6 to 2.6.1, but I am building my project using the provided .aar files. Shouldn't these include the proper .jni libs?

```
compile 'com.quickblox:quickblox-android-sdk-core:2.6.1@aar'
compile("com.quickblox:quickblox-android-sdk-chat:2.6.1@aar") {
    transitive = true
}
compile 'com.quickblox:quickblox-android-sdk-videochat-webrtc:2.6.1@aar'
```

**Comment by tatanka987** [comment]
hello @AustrianDudes,  no, .aar files not contain .jni libs, you must manually add this libs to your project

**Comment by RomanPronin** [comment]
Long time inactivity.
