### ISSUE TITLE
Hello everyone I have a problem with push notifications.

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-android#134]
The application works in all parts perfectly except for notifications.

In the dashboard quickblox there are no subscriptions for notifications.

What should I do?

**Comment by tatanka987** [comment]
hello @EminDemiri, did you perform [this instruction ](http://quickblox.com/developers/How_to_generate_API_key_and_set_it_in_QuickBlox_admin_panel)? If yes, please provide your logs from start login to complete all requests (I need request and response of creating subscription)

**Comment by EminDemiri** [comment]
Hi @tatanka987, could this be the cause?

10-27 12:35:38.605 13246-13246/com.emindemiri.talkme I/GMPM: App measurement is starting up, version: 8487
10-27 12:35:38.605 13246-13246/com.emindemiri.talkme I/GMPM: To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
10-27 12:35:39.045 13246-13246/com.emindemiri.talkme E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
10-27 12:35:39.065 13246-13246/com.emindemiri.talkme E/GMPM: Scheduler not set. Not logging error/warn.
10-27 12:35:39.450 13246-13290/com.emindemiri.talkme E/GMPM: Uploading is not possible. App measurement disabled

**Comment by EminDemiri** [comment]
@tatanka987 can you help me?

**Comment by tatanka987** [comment]
@EminDemiri did you set data to field "devPushRegistrationAppID" (or "prodPushRegistrationAppID" if you use build type release) in file gradle.properties of module Q-municate_app?

**Comment by EminDemiri** [comment]
Hi @tatanka987 i set you both devPushRegistrationAppID that prodPushRegistrationAppID

**Comment by tatanka987** [comment]
@EminDemiri  what version of com.google.android.gms:play-services-gcm do you use?

**Comment by EminDemiri** [comment]
@tatanka987 I have not modified version is still 8.4.0

**Comment by tatanka987** [comment]
@EminDemiri  try to create manually new string resource R.string.google_app_id in module Q-municate_app and set to this field data from devPushRegistrationAppID

**Comment by EminDemiri** [comment]
@tatanka987 I added the string resource, but still does not register the device.

I'll place post the log if you tell me the string to search in particular

**Comment by EminDemiri** [comment]
I created another project taking q-be communicated and without changing anything, I just sompilato the property of the files.

filtering the log with "on" getting this string:

 W/FA-SVC: Measurement Service called with invalid id version: "My api key"

**Comment by EminDemiri** [comment]
Can someone help me?

Today I created a new project without making any changes only by filling out the property of files, chat and login via twitter digits works but I still do not see in the subscriptions of quickblox administrations panel.

If maybe you can give me a little tutorial on how to create the google api key, with the new version, because that which is present in the documentation refers to the old gcm now if you Cerrca enable gcm google automatically redirects to Firebase.

maybe you can help me @tatanka987

**Comment by tatanka987** [comment]
hello @EminDemiri you can create application in [Firebase developer console](console.firebase.google.com), then generate google-services.json file with your credentials. Copy from google-services.json value of field "project_number" to your gradle.properties file to field devPushRegistrationAppID (prodPushRegistrationAppID) and value "current_key" set in QuickBlox admin panel to "Google Cloud Messaging (GCM) API key" section.

**Comment by RomanPronin** [comment]
Long time inactivity.

**Comment by wazowski78** [comment]
Hello,
I have the same issue with Android Notifications, I have create the application in FireBase, and generated the JSON file, I have follow the steps copying from google-services.json value of field "project_number" to your gradle.properties file to field devPushRegistrationAppID (prodPushRegistrationAppID) and value "current_key" set in QuickBlox admin panel to "Google Cloud Messaging (GCM) API key" section.
I have test "current key" with the JSON file data, the firebase console old server key, and the new firebase new server key. And nothing, the send script from Quickblox app console does not arrive to Android devices. In fact, the device is not subscribed to any channel. 
But if I test the firebase console send notification script, the notifications arrives to the device.
I can not figure out what is happening, can you help me please?
