### ISSUE TITLE
can't login/signup

### ISSUE THREAD

**Issue by eggysudianto** [QuickBlox/q-municate-android#138]
can't login/signup, using phone number or email or facebook...

**Comment by RomanPronin** [comment]
What version Q-municate do you use? And show us logs with requests and responses. Give us more detail info about your problem. Also have a look carefully at [this](https://quickblox.com/developers/Q-municate#Q-municate_Android).

**Comment by iman2420** [comment]
`startSignUpActivity` not used in your [link](https://github.com/QuickBlox/q-municate-android).
And `SignUpButton` not found

**Comment by iman2420** [comment]
when `resultAction=signup_action`        command is NULL

            ` if (intent != null && (action = intent.getAction()) != null) {
            Log.d(TAG, "service started with resultAction=" + action);
            ServiceCommand command = serviceCommandMap.get(action);
            if (command != null) {
                startAsync(command, intent);
            }else {
                Log.d(TAG, "startAsync command is NULL");
            }
        }`

**Comment by RomanPronin** [comment]
Closed, duplicate. Can't signup #222

**Comment by iman2420** [comment]
@RomanPronin You have not yet answered my question. in #222
