### ISSUE TITLE
Forgot password email

### ISSUE THREAD

**Issue by ganeshub** [QuickBlox/q-municate-android#139]
Is email sending is supported in Quickblox ?

I have tried to reset password with a test account email, Q-municate says Mail has been sent but I didn't receive any.

**Comment by ganeshub** [comment]
Mail is receiving if the mailid didn't get the dot(.) character in it.

For example, 
mymailid@gmail.com works but mymailid.quickblox@gmail.com is not.

**Comment by RomanPronin** [comment]
Hello @ganeshub. We recommend use the latest version Q-municate. Also, please, provide us logs with issue.

**Comment by tatanka987** [comment]
close, long time inactivity
