### ISSUE TITLE
update apps sources sdk to the latest versions 3.2.0 please 

### ISSUE THREAD

**Issue by sisqi** [QuickBlox/q-municate-android#140]
update apps sources sdk to the latest version "3.2.0" please

**Comment by tatanka987** [comment]
in next release Q-municate we will update sdk to latest version, now you can get q-municate with updated sdk from technical branch [update_sdk_3_2_0](https://github.com/QuickBlox/q-municate-android/tree/update_sdk_3_2_0) But this branch not contains new features of sdk, only updates to latest version and some fixes after updating.
