### ISSUE TITLE
Push Notification in User's Timezone

### ISSUE THREAD

**Issue by ganeshub** [QuickBlox/q-municate-android#141]
Hi,

Is it possible to send a push notification to a particular user and schedule the push notification based on that user's timezone ?

So that user will receive the push notification in his timezone like for example 9 AM.

Thanks

**Comment by ganeshub** [comment]
Reference: http://blog.parse.com/announcements/local-push-because-its-5-oclock-somewhere/

**Comment by tatanka987** [comment]
hello @ganeshub, QuickBlox server sends push notifications by UTC time zone. Try save time zone to QBUser's custom parameters (e.g. after success login)  and send deferred push notifications considering time zone of recipient.

**Comment by ganeshub** [comment]
@tatanka987 Thanks
