### ISSUE TITLE
How to send any file? 

### ISSUE THREAD

**Issue by ProgrammerNinja** [QuickBlox/q-municate-android#155]
How to send any file? because currently we can send only **images,** **videos and audio**! so i want to have it compatible with all files! any guidance plz?

**Comment by RomanPronin** [comment]
It's possible to add attachments to message: For example: image, audio file or video file. We don't have any restrictions here - you can attach any type of file. Look at this [link](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Send_and_receive_a_message_with_attachment).

**Comment by ProgrammerNinja** [comment]
any code? that can help me out?cause i partially can understand that link's instruction

**Comment by RomanPronin** [comment]
For example:
 ```
        QBChatMessage chatMessage = new QBChatMessage();
        QBAttachment attachment = new QBAttachment("photo");
        attachment.setId("123456789");
        attachment.setName("attachmentName");
        attachment.setContentType("image/jpg");
        attachment.setUrl("http://image.url.com");

        chatMessage.setBody("Message with attachment body");
        chatMessage.addAttachment(attachment);
```
Or upload file [like this](http://quickblox.com/developers/SimpleSample-content-android#Upload_file) and send it with attachment
```
QBContent.uploadFileTask(file, isPublic, new QBEntityCallback<QBFile>() {
    @Override
    public void onSuccess(QBFile qbFile, Bundle bundle) {
        // create a message
        QBChatMessage chatMessage = new QBChatMessage();
        chatMessage.setSaveToHistory(true); // Save a message to history
 
        // attach a txt
        QBAttachment attachment = new QBAttachment("txt");
        attachment.setId(qbFile.getId().toString());
        chatMessage.addAttachment(attachment);
 
        // send a message
        // ...
    }
```

**Comment by ProgrammerNinja** [comment]
Ok thanks! but one last help (im a newbie) 
Can tell me where to add this code in q-municate project?

**Comment by RomanPronin** [comment]
For example you can look at classes QBBaseChatHelper - there is creation of QBAttachment. Or QBGroupChatHelper, QBPrivateChatHelper with QBContent.uploadFileTask.

**Comment by ProgrammerNinja** [comment]
Hmmm... Can u guide me like, give me a working code of this?that would be awesome of you!

**Comment by ProgrammerNinja** [comment]
Anyone? who can help me out~!

**Comment by tatanka987** [comment]
close, long time inactivity
