### ISSUE TITLE
Disable group member to add users

### ISSUE THREAD

**Issue by ProgrammerNinja** [QuickBlox/q-municate-android#156]
How to disable group members to add users,i want only the group owner to add and remove users

**Comment by ProgrammerNinja** [comment]
Can anyone help me please! I want to know how to assign all the powers to just the admin!

**Comment by tatanka987** [comment]
hello @ProgrammerNinja, for it you can:
1) add new field to Dialog model with id of dialog's creator. 
2) add to method [createLocalDialog](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_core/src/main/java/com/quickblox/q_municate_core/utils/ChatUtils.java#L178) code for saving owner's id. Dialog's owner id value you can get from QBChatDialog:
Integer ownerId = chatDialog.getUserId();
3) increment DB's version (for removing old DB and create new).

On UI you can show "Add friend to Chat" menu item only for dialog's owner.

**Comment by ProgrammerNinja** [comment]
Hmmm..Can you please write the script? and tell me where to place it?

**Comment by BrianaHawks** [comment]
@tatanka987 Can you explain a bit more? Even I need this feature

**Comment by BrianaHawks** [comment]
@tatanka987 please can you guide me with a example :)

**Comment by tatanka987** [comment]
close, long time inactivity

**Comment by leena12345** [comment]
I got null ..
chatDialog.getUserId()
