### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by sawattoo** [QuickBlox/q-municate-android#16]
I am facing a problem when ever i tried to call audio or video calls. i cant listen  other user voice. and same with him.. some time on one side i listen voice which is so much broken. pl z help me to get ride of this.

**Comment by devwill** [comment]
i have a same problem!

**Comment by rafalzawadzki** [comment]
Same with me...

**Comment by dimitrireef** [comment]
did you find a solution, i am facing same issue
