### ISSUE TITLE
"Could not resolve all dependencies for configuration ':Q-municate_app:_debugApkCopy'" and "Could not find com.afollestad:material-dialogs:0.7.8.1."

### ISSUE THREAD

**Issue by Loborro** [QuickBlox/q-municate-android#167]
I was a few months inactivo in my android app, but no that i need to do some changes, i recieve this error when try to run the aplication:

Error:A problem occurred configuring project ':Q-municate_app'.
> Could not resolve all dependencies for configuration ':Q-municate_app:_debugApkCopy'.
   > Could not find com.afollestad:material-dialogs:0.7.8.1.
     Required by:
         q-municate-android:Q-municate_app:unspecified

![captura de pantalla 2017-02-08 a las 0 09 29](https://cloud.githubusercontent.com/assets/11675323/22725481/4a40ab10-ed93-11e6-9a4c-81200e3f280d.png)

Please i need some help.

**Comment by RomanPronin** [comment]
Hi @Loborro, in Q-municate_app/build.gradle you need replace com.afollestad:material-dialogs dependency with: 
```
compile 'com.afollestad.material-dialogs:core:0.9.0.1'
```
also in Q-municate_app/src/main/res/values/themes.xml delete lines with:
```
    <item name="homeAsUpIndicator">@drawable/abc_ic_ab_back_mtrl_am_alpha</item>
```

**Comment by tatanka987** [comment]
close, solved
