### ISSUE TITLE
Push Notifications Do NOT work in this Q-municate Android version.

### ISSUE THREAD

**Issue by wazowski78** [QuickBlox/q-municate-android#169]
Hello,
I have the same issue #134 with Android Notifications, I have create the application in FireBase, and generated the JSON file, I have follow the steps copying from google-services.json value of field "project_number" to your gradle.properties file to field devPushRegistrationAppID (prodPushRegistrationAppID) and value "current_key" set in QuickBlox admin panel to "Google Cloud Messaging (GCM) API key" section.
I have test "current key" with the JSON file data, the firebase console old server key, and the new firebase new server key. And nothing, the send script from Quickblox app console does not arrive to Android devices. In fact, the device is not subscribed to any channel.
But if I test the firebase console send notification script, the notifications arrives to the device.
I can not figure out what is happening, can you help me please?

**Comment by aliumujib** [comment]
to fix this issue, follow these steps
1. Put the old server key in the Quickblox admin dashboard and then also set the keys in the gradle.properties file.
2. Go the the class "com.quickblox.q_municate.tasks.QBGCMRegistrationTask"
3. In the "getRegistrationId()" method, look for the line of code "gcm.register();"
4. Supply the register method with the senderID from your firebase project console. It is the number beside the server key. Make it a string by putting it in quotes and supply it to the gcm.register method so it looks like this gcm.register("1234567890");
5. Run the app after UNINSTALLING and then check the dashboard if your user successfully subscribed. Please confirm that it works. It worked for me tho.

Regards,
Mujib.

**Comment by wazowski78** [comment]
Hello,
I have follow the aliumujib steps in the previous post and it keeps the same issue. I can test firebase console Push Notifications with success, but the user is not subscribed to Quikcblox GCM channel. 

I have modified an old project without success, and I have make a new one project and configured every variable as new, new Android Studio project, new GCM google api project and New FireBase project too, without success.

So I do not know why Firebase sends the push nots, and the app receives them, but the user is not subscribed at all.

I need some help here.

**Comment by aliumujib** [comment]
Hello wazowski78,
Interestingly those steps worked for me but before that, I discovered the error by modifying the method signature of "getRegistrationId()". If you look at the method "getRegistrationID" it throws an Exception that is handled somewhere that I didn't bother to fish out, instead, I removed the "throws IOException" line from the code so that I could control where the exception is thrown and printing the error to the log. So the method definition effectively goes from:

public void getRegistrationID(...) throws IOException

 to 

public void getRegistrationID(...) 

by doing that the IDE (Android Studio) prompts you to catch the exception where it occurs inside the method and handle it yourself. You can use that to fish out the error and then go from there. Just remember to change back when you're done. Let me know how that goes.

Regards,
Mujib.

**Comment by wazowski78** [comment]
I will do it but the method is not throwing an exception, in fact I get a RegistrationID, it is very weird, because iOS notifications are working properly from Quickblox notification sender in Test and Live, and the subscription works as well. But Android notifications are only working from firebase notification sender. I think I will use other solution, because this is going to be quite long for me.

**Comment by RomanPronin** [comment]
Hello @wazowski78, there is [Auto subscription](https://quickblox.com/developers/SimpleSample-messages_users-android#Setup_Push_Notifications_SDK_3.2_-_Auto_subscription) feature beginning from version SDK 3.2.0. Also you can take a look at [sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-pushnotifications) with this feature implemented.

**Comment by wazowski78** [comment]
Hi, and thank you for your reply!
I think, I may fail but, the last public Q-municate SDK is 2.1, so the Auto-subscription does not work. As I said before, it is possible I misunderstood something, right?
I have see the link of Auto-subscription you have tell me, but the results are the same or worst, because instead of depurate one Android app, I have to modify the complete solution for iOS too. 
Of course I know Q-municate is a template and share to us for free and we should not ask for updates, but at this moment the cross functioning with Push Nots between iOS and Android are not working.

And what I think is a bug for Android Q-municate version is that Push Notifications subscription is not working.

**Comment by RomanPronin** [comment]
In the near future will be released new version Q-municate with latest version SDK. So, stay tuned!

**Comment by wazowski78** [comment]
So the problem exists right now, Q-municate is and obsolete demo app, and the solution for this issue is wait for an update or a DIY option.

**Comment by ajthinking** [comment]
@RomanPronin , that sounds good! Can you give be more specific on "near future" release date when this will be resolved? Cheers.

**Comment by RomanPronin** [comment]
Approximately, new version Q-mun will be released in about a month.

**Comment by Widiyanto** [comment]
@wazowski78 I have same issue

**Comment by tatanka987** [comment]
Please remove your app and install it again, then signin to the app and provide us full logs from start app to finish loading all dialogs.

**Comment by tatanka987** [comment]
long time inactivity

**Comment by Jinqianv** [comment]
the android version is not subscribing for push notification with new firebase version(11.0.4) now.

**Comment by Jinqianv** [comment]
I can not receive any push from qb admin panel or firebase admin panel.
Pls help me

**Comment by RomanPronin** [comment]
Hi, @Jinqianv. How did you update firebase version? You should follow push [guide](https://quickblox.com/developers/SimpleSample-messages_users-android#Setup_Push_Notifications_SDK_3.2_-_Auto_subscription). Namely, in order to use version higher than in SDK, you should just add explicit dependency.
