### ISSUE TITLE
The amount of comments to the code is to damn low

### ISSUE THREAD

**Issue by brainmaniac** [QuickBlox/q-municate-android#174]
Thank you for doing this open-source code base. It is good but please:

![to damn low](https://cloud.githubusercontent.com/assets/13656814/24008871/515d7b56-0a73-11e7-844c-dfb8db6d5a82.png)

**Comment by tatanka987** [comment]
hello @brainmaniac we work on it, please wait next release

**Comment by brainmaniac** [comment]
@tatanka987 Okok looking forward to it! Thank you for fast reply!

**Comment by brainmaniac** [comment]
Opps this was actually meant for the web platform @Vladlukhanin! Sorry @tatanka987
