### ISSUE TITLE
how to start the project?

### ISSUE THREAD

**Issue by wuichen** [QuickBlox/q-municate-android#18]
I tried to open q_municate_app and q_municate_core,  neither of them are showing me the java or res files for me to edit, and I cant run the project. There seemed to be some gradle build errors? please help me on starting the project

**Comment by migueltarga** [comment]
Just import the whole project into android studio

**Comment by vinaytumbemane** [comment]
What we need to change(like package name) to build our own app and post on google store.
I am unable to install both q-municate app and my app, built using q-municate-android-sdk
