### ISSUE TITLE
Global contact is not show

### ISSUE THREAD

**Issue by rohitrathore** [QuickBlox/q-municate-android#184]
Can't find any Global 
![2c056b88a1c103682111ffaee1e3b617f0b2bac1ecc9ea4981 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/28044822/25426426/b52c8800-2a8c-11e7-987e-1e89491361df.jpg)
contact by my Quickblox  api , my quickblox in any number registered

**Comment by tatanka987** [comment]
Q-municate searches by Full Name, if you want to search by phone number, you have to do some changes in source code.
