### ISSUE TITLE
Any plans to support Quickblox v 2.2.*?

### ISSUE THREAD

**Issue by woutergoossens** [QuickBlox/q-municate-android#20]
Any plans to support Quickblox v 2.2.*?

Much appreciated!

**Comment by soulfly** [comment]
Do you have any issues with manual update to 2.2.*?

**Comment by vinaytumbemane** [comment]
For demo we used q-municate 1.0.10 as base version.
Now we are going to develop stable product.
Is version 1.0.10 is stable or latest available version is stable?
Which is recommended for developing product. Its urgent.
