### ISSUE TITLE
Push notification is not working on android version (q-munictae)

### ISSUE THREAD

**Issue by 2vikki** [QuickBlox/q-municate-android#21]
I made a clone of q-municate version but push notification is not working on the app.I already refer this link http://quickblox.com/developers/SimpleSample-messages_users-android#Setup_GCM pls give me support for this problem

**Comment by soulfly** [comment]
Can you check the Admin panel. Users module
each user can have push subscriptions in his profile

If not then something wrong with push subscription logic

**Comment by blacksuite12** [comment]
I have set up the GCM and admin panel correctly but still not getting any notifications

**Comment by AyushiBShah** [comment]
Hi I am also facing same issue, @soulfly can you please look into notifications issue . I have configured them but recipient end I am not able to fetch the GCM
