### ISSUE TITLE
Please help me with this issue 

### ISSUE THREAD

**Issue by fahadhballoy** [QuickBlox/q-municate-android#211]
Error:Execution failed for task ':Q-municate_app:mergeDevReleaseResources'.
> C:\q-municate-android-master\Q-municate_app\build\generated\res\resValues\dev\release\values\generated.xml: Error: The resource name must start with a letter

It shows the resource name must start with with a letter while generating signed apk

**Comment by tatanka987** [comment]
Did you fallow [this guide](https://quickblox.com/developers/Q-municate#Q-municate_Android)? Please specify your steps for building .apk

**Comment by fahadhballoy** [comment]
yeah i follow these but it shows the same error

**Comment by tatanka987** [comment]
what about building .apk? Do you just select build variant 'release' and press 'Run' button or other ways?

**Comment by fahadhballoy** [comment]
yeah the same way select build variant and release

**Comment by fahadhballoy** [comment]
https://play.google.com/store/apps/details?id=com.fahadhballoy.fine
