### ISSUE TITLE
Unable to signUp

### ISSUE THREAD

**Issue by ADTLabs** [QuickBlox/q-municate-android#212]
I am unable  to signup . Loader keeps on loading.

**Comment by tatanka987** [comment]
@ADTLabs please provide us more information about your issue: steps to reproduce, logs, what changes did you do in code, etc.

**Comment by ADTLabs** [comment]
i m calling your function"startSignUpActivity()" which is defined in LandingActivity.java on a button click .

While clicking on button i got following logs

 I/TableUtils: executed create table statement changed 1 rows: CREATE TABLE `dialog_occupant` (`dialog_id` INTEGER REFERENCES dialog(dialog_id) ON DELETE CASCADE , `dialog_occupant_id` INTEGER PRIMARY KEY AUTOINCREMENT , `dialog_occupant_status` VARCHAR NOT NULL , `id` INTEGER NOT NULL , UNIQUE (`dialog_id`,`id`) ) 
06-29 16:48:12.256 8129-8129/com.quickblox.q_municate I/TableUtils: creating table 'dialog_notification'
06-29 16:48:12.258 8129-8129/com.quickblox.q_municate I/TableUtils: executed create table statement changed 1 rows: CREATE TABLE `dialog_notification` (`body` VARCHAR , `created_date` BIGINT , `dialog_notification_id` VARCHAR , `dialog_occupant_id` INTEGER REFERENCES dialog_occupant(dialog_occupant_id) ON DELETE CASCADE , `state` VARCHAR , `type` VARCHAR ,  UNIQUE (`dialog_notification_id`), PRIMARY KEY (`dialog_notification_id`) ) 
06-29 16:48:12.258 8129-8129/com.quickblox.q_municate I/TableUtils: creating table 'attachment'
06-29 16:48:12.260 8129-8129/com.quickblox.q_municate I/TableUtils: executed create table statement changed 1 rows: CREATE TABLE `attachment` (`additional_info` VARCHAR , `attachment_id` VARCHAR , `blob_id` INTEGER , `duration` INTEGER , `height` INTEGER , `name` VARCHAR , `remote_url` VARCHAR , `size` DOUBLE PRECISION , `type` VARCHAR , `width` INTEGER ,  UNIQUE (`attachment_id`), PRIMARY KEY (`attachment_id`) ) 
06-29 16:48:12.260 8129-8129/com.quickblox.q_municate I/TableUtils: creating table 'message'
06-29 16:48:12.262 8129-8129/com.quickblox.q_municate I/TableUtils: executed create table statement changed 1 rows: CREATE TABLE `message` (`attachment_id` VARCHAR , `body` VARCHAR , `created_date` BIGINT , `dialog_occupant_id` INTEGER REFERENCES dialog_occupant(dialog_occupant_id) ON DELETE CASCADE , `message_id` VARCHAR , `state` VARCHAR ,  UNIQUE (`message_id`), PRIMARY KEY (`message_id`) ) 
06-29 16:48:12.318 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'social' with 'DELETE FROM `social`
06-29 16:48:12.334 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'friend' with 'DELETE FROM `friend`
06-29 16:48:12.348 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'user_request' with 'DELETE FROM `user_request`
06-29 16:48:12.359 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'dialog' with 'DELETE FROM `dialog`
06-29 16:48:12.361 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'dialog_occupant' with 'DELETE FROM `dialog_occupant`
06-29 16:48:12.362 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'dialog_notification' with 'DELETE FROM `dialog_notification`
06-29 16:48:12.363 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'attachment' with 'DELETE FROM `attachment`
06-29 16:48:12.394 8129-8129/com.quickblox.q_municate I/TableUtils: clearing table 'message' with 'DELETE FROM `message`
06-29 16:48:12.412 8129-8129/com.quickblox.q_municate D/BaseActivity: onAttachFragment
06-29 16:48:12.480 8129-8129/com.quickblox.q_municate D/QBService: onStartCommand
06-29 16:48:12.480 8129-8129/com.quickblox.q_municate D/QBService: service started with resultAction=signup_action
06-29 16:48:16.332 8129-9331/com.quickblox.q_municate V/FA: Inactivity, disconnecting from the service

**Comment by tatanka987** [comment]
in newest versions of Q-municate we removed possibility to create new users by e-mail, if you need this functionality, you have to write this logic himself

**Comment by ADTLabs** [comment]
I tried below code for sign up ,its working fine  

 void signUpserver(final QBUser qbUser)
    {
        QBUsers.signUp(qbUser).performAsync(new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser user, Bundle args) {
               Log.i("Signup","success");
                performLoginSuccessAction(qbUser);
            }

            @Override
            public void onError(QBResponseException error) {
                // error
                hideProgress();
                AuthUtils.parseExceptionMessage(SignUpActivity.this, error.getMessage());
                Log.i("Signup","error");
            }
        });

    }

after getting logged in i m getting '{"errors":{"base":["Forbidden. Need user."]}}' while uploading Avatar Pic. Can you assist me where i m doing mistake ?

**Comment by tatanka987** [comment]
after success signUp you have to update current session to make it as 'user session', for it you have to call QBUsers.signIn(qbUser) and then you can update user, get dialogs for this user, etc

**Comment by ADTLabs** [comment]
I tried this but its not working i guess we call more function  as i can see there are more functions are getting called after **login** success 
  CoreSharedHelper.getInstance().saveUsersImportInitialized(true);

                        String password = userPassword;

                        if (!hasUserCustomData(qbUser)) {
                            qbUser.setOldPassword(password);
                            try {
                                updateUserSync(qbUser);
                            } catch (QBResponseException e) {
                                Log.d(TAG, "updateUser " + e.getMessage());
                                throw Exceptions.propagate(e);
                            }
                        }

                        qbUser.setPassword(password);

                        saveOwnerUser(qbUser);

                        AppSession.startSession(qbUser);

**Comment by ADTLabs** [comment]
After successful signup , i called the login function , its works .
thanks
