### ISSUE TITLE
Issue on chat while attaching image 

### ISSUE THREAD

**Issue by ADTLabs** [QuickBlox/q-municate-android#215]
Image is getting repeated after attaching the image on private Chat dialog .

Have a look 
![sdgsdg](https://user-images.githubusercontent.com/12840292/28169468-0425948c-6800-11e7-9895-b5d7d36d4068.png)

**Comment by ADTLabs** [comment]
I haven't got any feedback from your side

**Comment by tatanka987** [comment]
hi @ADTLabs, sorry for long time answer. On screenshot I can see two different messages with different time. Did you do any changes in source code? Please provide more info for localization this issue (full logs, steps to reproduce etc.).

**Comment by ADTLabs** [comment]
no i haven't changed source code . Also, I have i m getting type of error while using your sample that you have provided. 

For reproduce 

open chat screen , send one picture from gallery or camera ,Once image sent again send one more image, you will get same issue

**Comment by ADTLabs** [comment]
Are you there?? Please assist me as my project is in pending mode ..

**Comment by tatanka987** [comment]
our testers could not reproduce this issue on release build,  we can't help you without additional information, so please provide us more information as I asked above (full logs from start application to getting this error, detail steps to reproduce this issue and other information which will help us localize issue).

**Comment by ADTLabs** [comment]
It's strange for me to hear such reply from your side as I was not expecting this even though it's your own code that I replicate into my project & for the issue details I already shared the issue which I captured from your demo code itself & if you need the Log of your demo project or mine then I can share those from my side but I am sure your little time can save lot things.

Thanks

**Comment by ADTLabs** [comment]
[log double image.txt](https://github.com/QuickBlox/q-municate-android/files/1158719/log.double.image.txt)
Attached log .Have a look.

**Comment by tatanka987** [comment]
thank you for a log, looks like we reproduced this case (but not just open chat, need  close and reopen app again before sending attach), we will try fix it in next release

**Comment by ADTLabs** [comment]
Sound great! Let us know by when we can expect the next release for this fixation update now.

**Comment by ADTLabs** [comment]
It would be appreciable if you can please let us know a date for the next release of this fixation as we are on dark side for now because unable to proceed further.

**Comment by ADTLabs** [comment]
Hi guys, awaiting for your confirmation on the new version release with the issue fixation. Would be appreciable to you guys if you can come with a date as on your input we can only proceed further.

Looking forward to hear from you on to this.

Thanks,
Ravi
