### ISSUE TITLE
Push notifications for chats with offline users, not implemented? 

### ISSUE THREAD

**Issue by alexfdz** [QuickBlox/q-municate-android#217]
Hi,
I have forked and configured successfully an instance of q-municate-android with a quickblox backend (great work!).

I can see push notifications working in different ways:
* From the quickblox admin dashboard
* From the firebase dashboard
* When an users starts a call/videocall with an offline user (ConversationCallFragment#sendPushAboutCall)

The weird thing is that I cannot see (in the q-municate-android code) any push notification being triggered when an user sends a message to an offline user, but is a feature that definitely works in the q-municate-android "official" version in Google Play.

Is a server-side hook? Is implemented in a different branch?

Thanks!

**Comment by RomanPronin** [comment]
Hi, @alexfdz. If your opponent is offline while you sending a message - he will automatically receive push notification. Look for more info [here](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Push_notifications_to_the_offline_users).

**Comment by alexfdz** [comment]
Thanks @RomanPronin!
