### ISSUE TITLE
How to join every new user in PUBLIC_GROUP?

### ISSUE THREAD

**Issue by iman2420** [QuickBlox/q-municate-android#225]
I create a **PUBLIC_GROUP** from [Admin_Panel](https://admin.quickblox.com/apps).
I want every user who installed the app. Automatically join this PUBLIC_GROUP.
QuickBlox SDK version is 3.3.5.
i use this code:

      `QBRestChatService.getChatDialogs(QBDialogType.PUBLIC_GROUP, qbRequestGetBuilder).performAsync(
                    new QBEntityCallback<ArrayList<QBChatDialog>>() {
                        @Override
                        public void onSuccess(ArrayList<QBChatDialog> result, Bundle params) {
                            int totalEntries = params.getInt("total_entries");
                            AppLog.Log(TAG, "getChatDialogs totalEntries onSuccess "+totalEntries);
                            for (QBChatDialog parcelableQBDialog : result) {
                                AppLog.Log(TAG, "QBChatDialog NAME=" + parcelableQBDialog.getName() + " QBChatDialog TYPE= " + parcelableQBDialog.getType());
                                if (parcelableQBDialog.getType().toString().equals("PUBLIC_GROUP")){
                                    joinToPublicGroupIman(parcelableQBDialog);
                                }
                            }
                        }

                        @Override
                        public void onError(QBResponseException responseException) {
                            AppLog.Log(TAG, "getChatDialogs totalEntries onError "+responseException.getMessage());

                        }
                    });`
And  **joinToPublicGroupIman** method:

    `   public void joinToPublicGroupIman(QBChatDialog PublicGroup) {
        QBDialogRequestBuilder requestBuilder = new QBDialogRequestBuilder();
        int userId = CoreSharedHelper.getInstance().getUserId();
        AppLog.Log(TAG, "Current user ID:_ " + userId);
        requestBuilder.addUsers(userId); // add current user
        QBRestChatService.updateGroupChatDialog(PublicGroup, requestBuilder).performAsync(new QBEntityCallback<QBChatDialog>() {
            @Override
            public void onSuccess(QBChatDialog qbChatDialog, Bundle bundle) {
                AppLog.Log(TAG, "updateGroupChatDialog onSuccess ID:_ ");
            }

            @Override
            public void onError(QBResponseException e) {
                AppLog.Log(TAG, "updateGroupChatDialog user onError:_ " + e.getMessage());
            }
        });
    }`

But i got this error:

`onError:_ You don't have appropriate permissions to perform this operation`

Because, by default, I could not see the **PUBLIC_GROUP** that I had already built, I had to use the **getChatDialogs** command.

Please help me about this.

**Comment by tatanka987** [comment]
you not need to join to PUBLIC_GROUP dialog, after first step (getChatDialogs) you can chatting in all PUBLIC_GROUP dialogs

**Comment by iman2420** [comment]
@tatanka987 thank you. So how do I show it to the user?

**Comment by tatanka987** [comment]
in success callback you can update your adapter for displaying loaded dialogs, then user can click on some dialog and start chatting as in common dialog without any limits

**Comment by iman2420** [comment]
@tatanka987 please show me with JAVA code.

**Comment by tatanka987** [comment]
sorry, but I don't know logic of your app, if you use Q-municate as base, you can do it in method [onLoadFinished](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_app/src/main/java/com/quickblox/q_municate/ui/fragments/chats/DialogsListFragment.java#L372) or if you use Chat-sample as base, you can do it  in method [loadDialogsFromQb](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-chat/src/main/java/com/quickblox/sample/chat/ui/activity/DialogsActivity.java#L357)

**Comment by iman2420** [comment]
I use Q-municate as base.
and i try to get group in **DialogsListFragment**... onViewCreated:

     `  @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        AppLog.Log(TAG, "onViewCreated");
        baseActivity.showSnackbar(R.string.dialog_loading_dialogs, Snackbar.LENGTH_INDEFINITE);
        QBRequestGetBuilder qbRequestGetBuilder = new QBRequestGetBuilder();
        qbRequestGetBuilder.setLimit(100);
        QBRestChatService.getChatDialogs(QBDialogType.PUBLIC_GROUP, qbRequestGetBuilder).performAsync(
                new QBEntityCallback<ArrayList<QBChatDialog>>() {
                    @Override
                    public void onSuccess(ArrayList<QBChatDialog> result, Bundle params) {
                        int totalEntries = params.getInt("total_entries");
                        AppLog.Log(TAG, "getChatDialogs totalEntries onSuccess " + totalEntries);
                        for (QBChatDialog parcelableQBDialog : result) {
                            AppLog.Log(TAG, "QBChatDialog NAME=" + parcelableQBDialog.getName() + " QBChatDialog TYPE= " + parcelableQBDialog.getType());
                            if (parcelableQBDialog.getType().toString().equals("PUBLIC_GROUP")) {
                               //TODO How to add this QBChatDialog to userList???
                            }
                        }
                    }

                    @Override
                    public void onError(QBResponseException responseException) {
                        AppLog.Log(TAG, "getChatDialogs totalEntries onError " + responseException.getMessage());

                    }
                });
    }`

**Comment by tatanka987** [comment]
in your code it can look like: 
```
ArrayList<DialogWrapper> wrappedDialogsList = new ArrayList<>(result.size());
        for (QBChatDialog chatDialog : result){
            DialogWrapper wrappedDialog = new DialogWrapper(baseActivity, dataManager, chatDialog);
            wrappedDialogsList.add(wrappedDialog);
        }

        dialogsListAdapter.setNewData(wrappedDialogsList);
```

But pay attention, you need to correct main Q-municate logic for full integration new functionality (save to DB, update dialog's list etc.)

**Comment by iman2420** [comment]
@tatanka987 I know you're angry for being amateur. But how can I do that?
