### ISSUE TITLE
How to change dialog body textView typeFace?

### ISSUE THREAD

**Issue by iman2420** [QuickBlox/q-municate-android#228]
I want to change dialog body textView typeFace. How to do it?
![image](https://user-images.githubusercontent.com/9848715/30238699-2e1139ac-9561-11e7-9eb2-fdf660849ae3.png)

**Comment by tatanka987** [comment]
@iman2420 please read our [documentation](https://github.com/QuickBlox/ChatMessagesAdapter-android/blob/master/README.md)

**Comment by iman2420** [comment]
@tatanka987 I read documentation. but i can not find any textView to change font and can not find any list item to setOnLongClickListener
QuickBlox SDK version is 3.3.5.
I use Q-municate as base.

**Comment by RomanPronin** [comment]
@iman2420, to change dialog body textView typeFace just create the next style:
`    <style name="TextViewTextMsg.Right">`
    `<item name="android:typeface">serif</item>`
 `   </style>`
