### ISSUE TITLE
No recipients. At least one user should be subscribed for 'gcm' (through SDK or REST API)

### ISSUE THREAD

**Issue by iman2420** [QuickBlox/q-municate-android#230]
I can not sent notifications from [Admin_Panel ](https://admin.quickblox.com)on live mode:

> No recipients. At least one user should be subscribed for 'gcm' (through SDK or REST API)

And in Testing mode i got success message but not receive   

please help me....

**Comment by anil-kumar-singh** [comment]
I am also getting the same error in live mode. Any Success?
