### ISSUE TITLE
How to get Chat Dialog By Id?

### ISSUE THREAD

**Issue by iman2420** [QuickBlox/q-municate-android#237]
Hi. i try to get Chat Dialog By Id at this code:

    `  QBRestChatService.getChatDialogById("59aefb2ca0eb475750844ae8").performAsync(new QBEntityCallback<QBChatDialog>() {
            @Override
            public void onSuccess(QBChatDialog qbChatDialog, Bundle bundle) {
                AppLog.Log(TAG, "getChatDialogById NAME=" + qbChatDialog.getName() + " QBChatDialog TYPE= " + qbChatDialog.getType());
            }

            @Override
            public void onError(QBResponseException e) {
                AppLog.Log(TAG, "getChatDialogById QBResponseException onError " + e.getMessage());
           
            }
        });`
but i got this Exception :
    

> QBResponseException onError Entity you are looking for was not found.

Why? 

- **59aefb2ca0eb475750844ae8** is an existing group ID. I'm not a member of it.

- Room jid = 61447_59aefb2ca0eb475750844ae8@muc.chat.quickblox.com

- Room Type = Group

**Comment by tatanka987** [comment]
are you sure that this dialog from your current app? can you check it in admin panel?

**Comment by iman2420** [comment]
@tatanka987 Yeah I'm sure. After several arrivals and exits to the application , the group chat is finally displayed!

[show this image](https://drive.google.com/file/d/0B3Zyfq5yagRPLWxxSFhWS0Ftd3M/view?usp=drivesdk)
