### ISSUE TITLE
IncomingCallFragment not show up in the destination device

### ISSUE THREAD

**Issue by iman2420** [QuickBlox/q-municate-android#241]
This is my LogCat in the destination device when start video call or audio call from source device:

    `D/SMACK: RECV (0): <message from="32321337-61447@chat.quickblox.com/android_ffffffff-e67c-8da2-041f-3d4729849042" id="1508785631543" xmlns="jabber:client" type="headline" to="34160878-61447@chat.quickblox.com"><extraParams xmlns="jabber:client"><callType>2</callType><platform>android</platform><callerID>32321337</callerID><signalType>call</signalType><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><sessionID>85173bea-bd21-45af-830c-899942e9e9df</sessionID><sdp>v=0
                          o=- 307620037835968978 2 IN IP4 127.0.0.1
                          s=-
                          t=0 0
                          a=group:BUNDLE audio
                          a=msid-semantic: WMS ARDAMS
                          m=audio 33360 UDP/TLS/RTP/SAVPF 103 111 9 102 0 8 105 13 110 113 126
                          c=IN IP4 52.31.10.80
                          a=rtcp:9 IN IP4 0.0.0.0
                          a=candidate:1148643132 1 udp 2122260223 192.168.43.1 56496 typ host generation 0 network-id 4 network-cost 10
                          a=candidate:3921644193 1 udp 2122194687 100.79.31.219 47306 typ host generation 0 network-id 3 network-cost 900
                          a=candidate:559267639 1 udp 2122136831 ::1 50811 typ host generation 0 network-id 2
                          a=candidate:1510613869 1 udp 2122063615 127.0.0.1 36507 typ host generation 0 network-id 1
                          a=candidate:2993069800 1 udp 1686052607 5.127.121.198 3070 typ srflx raddr 192.168.43.1 rport 56496 generation 0 network-id 4 network-cost 10
                          a=candidate:1761053717 1 udp 1685987071 5.127.121.198 1239 typ srflx raddr 100.79.31.219 rport 47306 generation 0 network-id 3 network-cost 900
                          a=candidate:1761053717 1 udp 1685987071 5.127.121.198 2827 typ srflx raddr 100.79.31.219 rport 47306 generation 0 network-id 3 network-cost 900
                          a=candidate:2993069800 1 udp 1686052607 5.127.121.198 2267 typ srflx raddr 192.168.43.1 rport 56496 generation 0 network-id 4 network-cost 10
                          a=candidate:3133886805 1 udp 41820159 52.31.10.80 33360 typ relay raddr 5.127.121.198 rport 1239 generation 0 network-id 3 network-cost 900
                          a=candidate:2027022022 1 udp 41885695 52.31.241.61 37220 typ relay raddr 5.127.121.198 rport 2267 generation 0 network-id 4 network-cost 10
                          a=candidate:4098403749 1 udp 25042687 52.31.10.80 48188 typ relay raddr 5.127.121.198 rport 3027 generation 0 network-id 3 network-cost 900
                          a=candidate:911350326 1 udp 25108223 52.31.241.61 62795 typ relay raddr 5.127.121.198 rport 2737 generation 0 network-id 4 network-cost 10
                          a=ice-ufrag:Pjyn
                          a=ice-pwd:gUHj++djMHknZLznxIc59hHd
                          a=ice-options:renomination
                          a=fingerprint:sha-256 1E:BD:FC:26:74:2B:C2:56:87:53:AD:E9:1B:B8:1B:26:3E:32:53:27:A7:D1:DE:0B:DE:5D:08:54:1C:E8:71:D4
                          a=setup:actpass
                          a=mid:audio
                          a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
                          a=sendrecv
                          a=rtcp-mux
                          a=rtpmap:103 ISAC/16000
                          a=rtpmap:111 opus/48000/2
                          a=rtcp-fb:111 transport-cc
                          a=fmtp:111 minptime=10;useinbandfec=1
                          a=rtpmap:9 G722/8000
                          a=rtpmap:102 ILBC/8000
                          a=rtpmap:0 PCMU/8000
                          a=rtpmap:8 PCMA/8000
                          a=rtpmap:105 CN/16000
                          a=rtpmap:13 CN/8000
                          a=rtpmap:110 telephone-event/48000
                          a=rtpmap:113 telephone-event/16000
                          a=rtpmap:126 telephone-event/8000
                          a=ssrc:626767409 cname:XTGR/EnadRJqW8RX
                          a=ssrc:626767409 msid:ARDAMS ARDAMSa0
                          a=ssrc:626767409 mslabel:ARDAMS
                          a=ssrc:626767409 label:ARDAMSa0
                          </sdp><version_sdk>3.3.5</version_sdk><opponentsIDs>
     <opponentID>34160878</opponentID></opponentsIDs></extraParams></message>
     D/QBASDK: Receive Video signal ' call', from User: 32321337, sessionId: 85173bea-bd21-45af-830c-899942e9e9df
     D/BaseClient.: Call offer message received from32321337`

This means the device receives the call, but does not display it. What is the cause of this?
QuickBlox SDK version is 3.3.5.
I use Q-municate as base.

**Comment by tatanka987** [comment]
Can you reproduce this issue on our build? If yes, please provide details steps to reproduce and logs if you have they. If this issue reproduced only on your build, check for initing QBCallChatHelper after success login to the chat.
