### ISSUE TITLE
I am getting this error of firebase auth but error is not going to solve in any way

### ISSUE THREAD

**Issue by roma50** [QuickBlox/q-municate-android#242]
I modified q-municate app(which is open source) GitHub code and I put my own credential to firebase auth but I am getting this error. I put all credential but still, I do not know what is the error.Please help me about this error how to solve this error. I put all these credential but still giving an error and also mentioned in the image about the error. Project ID: APP ID:
Package name:
These things i put in project. can anybody know what the error mentioned in image.
![whatsapp image 2017-10-26 at 1 04 34 pm](https://user-images.githubusercontent.com/33146053/32091338-88311b8e-baa8-11e7-8b20-163c52f5e211.jpeg)
Why this error is coming and how to sort out this issue. Please reply fast i am checking your services so that i can take your company premium services.

**Comment by tatanka987** [comment]
please see this solution https://stackoverflow.com/a/46970207/4850609

**Comment by roma50** [comment]
Unfortunately, Still verification is not going successfully after doing this step.
