### ISSUE TITLE
Login with Facebook not Working in Quickblox Q Municate Project.

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#247]
I downloaded the open-source code of Q-municate and successfully build and run that. But when I click on Login with Facebook, it is not working. It just shows the ProgressDialog and then shows **"Base Unexpected Signature".**

Just Found the SignUp Activity, but same problem it is not registering as well.

Please let me know what changes I need to do to run the Qmunicate Project in my Android
--

**Comment by tatanka987** [comment]
Did you make needed changes from [this guide ](https://quickblox.com/developers/Q-municate#Q-municate_Android), if yes, please provide us full log from start app to getting this error. Additionally check date and time on your device they must be set as Automatic and check current time zone.

**Comment by sheikhrashid** [comment]
I just fixed that. I followed the guide carefully an everything went fine.
