### ISSUE TITLE
Unable to Sign Up

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#248]
SignUp is not working, it just keep showing the progressBar. I even remove the "showProgress" but nothing is happening. Have you disabled that?

**Comment by tatanka987** [comment]
@sheikhrashid please provide us more information about your issue (steps to reproduce, logs, etc.)

**Comment by sheikhrashid** [comment]
I have downloaded the latest Qmunicate project. Successfully run that. I noticed that there was not any option for Sign Up button, but I managed to get that (button was hidden but code was available). So I managed to get that.

Now I fill Fullname, Email, password and go for Signup. It doesn't sign up the user to my Quickblox server. It just keep showing the ProgressBar and nothing happens.

Here is the full Log what happens when I press for signup after filling credentials. 
https://gist.github.com/sheikhrashid/6faf2fc55b3d08956a6a66b83402e754

**Comment by tatanka987** [comment]
SignUp function was deleted from latest version of Q-municate, and you need realize this functionality himself. As you can see in your logs, command QBSignUpCommand was started, but nothing happens. Try search in git history, how to restore SignUp functionality or try add it himself.

**Comment by sheikhrashid** [comment]
Can't you please give me the direction for the code?

**Comment by sheikhrashid** [comment]
I successfully signed up with help of this: https://github.com/QuickBlox/q-municate-android/issues/222

But there is not any option here to upload the Profile picture at time of signup. Can you guide me on this?
