### ISSUE TITLE
Connectivity issue in the application

### ISSUE THREAD

**Issue by roma50** [QuickBlox/q-municate-android#249]
There is connectivity issue in this application. Whenever open the application it takes times for connectivity. sometimes, there is no internet issue everything working fine on internet but only this app showing disconnected. There is big issue of connectivity of app. During opening the app takes time and also during using of app. How to solve this issue. How to make more fastest app and connectivity so that no need to wait long for connectivity and disconnected issues in spite of there is no any internet slow issue and Everything working fine on internet.
Please help me in this issue. Thanks

**Comment by leena12345** [comment]
Even I faced this issue. Is there any solution for it?
