### ISSUE TITLE
Is Call log for Audio and Video calls implemented in Q-Municate Android?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#251]
I want to know Is Call log for Audio and Video calls implemented in Q-Municate Android?

**Comment by AyushiBShah** [comment]
Hi you would have to implement as per my understanding of sdk. We implemented call logs on own for our application.

**Comment by sheikhrashid** [comment]
Yeah there is no call log. I have implemented successfully.

**Comment by AAPBD** [comment]
Thanks @sheikhrashid. Would you please share the code snippet for the call log? I need to implement it for one of my projects. Looking for your kind cooperation.

**Comment by sheikhrashid** [comment]
Hi @AAPBD.  What I did is a simple thing. I just added a new UI with some Views. Every time, I receive a new call, or I make a call. I populate the UI in a ListView. Simple :)

Just a UI Manipulation ;)

**Comment by AAPBD** [comment]
Would be great if you can share the code.
