### ISSUE TITLE
How to get Background Incoming call in Android Q-Municate 

### ISSUE THREAD

**Issue by roma50** [QuickBlox/q-municate-android#252]
I modified Q-Municate. But, in the background we just receive call notification like (ABC is calling you);
instead of call screen directly in background and during locked screen.

When, we click on notification that (ABC is calling you); then it first open the application then it show the incoming call screen.

But, how to show directly incoming call screen when app will be close and phone screen will lock. 
Please tell me How I can solve the solution of this issue. Thanks

**Comment by tatanka987** [comment]
As fast solution you can add starting command QBLoginChatCompositeCommand when call push was received (in class [ChatNotificationHelper.java](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_app/src/main/java/com/quickblox/q_municate/utils/helpers/notification/ChatNotificationHelper.java#L60)). Additionally for implementation showing call screen on lock screen you need learn Android documentation how to show Activity on lock screen. But pay attention, Q-municate is big project and we need more time for investigating and implementing this feature.

**Comment by roma50** [comment]
I already done above solution but not successful unfortunately
