### ISSUE TITLE
Maximum video size & Length of video uploading?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#256]
I want to know what is maximum video size and Length of video uploading in Quickblox Android SDK 3.3.5

**Comment by tatanka987** [comment]
> [Note: The maximum size of the uploaded file is 100 mb](https://quickblox.com/developers/Content#Upload_a_file)

Please read documentation before post issue.

**Comment by sheikhrashid** [comment]
I have already read the documentation. I just wanted to know is there limit for Length as well?

**Comment by tatanka987** [comment]
for attachments functionality used module Content it means other parameters of file (duration, width, hight, etc.) doesn't matter, only file size.
