### ISSUE TITLE
How can 'Incoming Call Push notfication' can come on FullScreen?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#257]
I am receiving push notifications successfully. But the problem is when audio or video call receives I want to open full IncomingCallFragment instead of Notification Bar.

I searched and found that it can be done by **event.setPushType(QBPushType.APNS_VOIP)**. I tried, but still not working.
Also I want to know I am working on Android and "APNS_VOIP" seems to be related to Apple.

**Comment by tatanka987** [comment]
This push works only on iOS and we added this type to Android SDK for support cross platform work (calls from Android to iOS). For your functionality you need start login to the chat and set call listeners when you got push about call. But Q-municate is big project and need investigate how to do this correct.

**Comment by sheikhrashid** [comment]
Thanks much for your reply
