### ISSUE TITLE
Users get offline ?

### ISSUE THREAD

**Issue by indikaanu83** [QuickBlox/q-municate-android#26]
When the app goes background it completely stops all the communications. As a result the other end users see this user as offline. Also while the app is in background, if the other end user sends a chat message the current user not get notified. Is this normal behavior of this app (q-municate) ?

**Comment by blacksuite12** [comment]
You are not the only one here. infact im also facing this problem for a week i have been still trying to find out how to send notifications to users using the GCM

**Comment by indikaanu83** [comment]
GCM is working. Only thing is you need have actual devices for this. As far as I know the emulator is no good for this. 
In quickblox control panel go to the Messages module. Then select the "Subscriptions" tab. In there you should see some entries. These are the GCM subscribed users in your quickblox application. Subscription happens with the login. Its there at  Mainactivity-Oncreate() method. Please check the attachment. Also you need to create a Google API application for this. 
Use this link to create your google api application

https://code.google.com/apis/console

![messages](https://cloud.githubusercontent.com/assets/5820748/8493288/fd3b1f20-210c-11e5-8cb8-9cdc51332484.png)

**Comment by blacksuite12** [comment]
I created a server api and assigned it as production and development and i do have actual devices and i do see those lines but no notifications, Can we please Communicate through a chat application? because its been almost a week and a few days and im still trying to fix this, Thank you

**Comment by indikaanu83** [comment]
Ok, Can you please give me your email ?. I can add you to my gtalk.

Thanks

**Comment by blacksuite12** [comment]
soap254@gmail.com

**Comment by robi10101298** [comment]
I need some help..Can you please add me?
