### ISSUE TITLE
Incorrect URL protocol

### ISSUE THREAD

**Issue by sami-abdul** [QuickBlox/q-municate-android#261]
When signing in with phone number, a toast appears saying "Incorrect URL protocol". This is the stack trace.

`12-11 21:25:36.569 5527-5527/com.quickblox.q_municate D/BaseAuthActivity: FirebaseAuthCallback onSuccess()
12-11 21:25:36.572 5527-20086/com.quickblox.q_municate D/QBASDK: Error occurred while parsing url :Protocol not found: /session.json
12-11 21:25:36.572 5527-20086/com.quickblox.q_municate D/QBASDK: Incorrect url protocol
12-11 21:25:36.572 5527-20086/com.quickblox.q_municate D/QBASDK: error result class rx.internal.operators.OnSubscribeMap$MapSubscriber
12-11 21:25:36.572 5527-20086/com.quickblox.q_municate D/QBASDK: PerformOnSubscribe:processOnError 
12-11 21:25:36.573 5527-5527/com.quickblox.q_municate D/BaseActivity: onAttachFragment
12-11 21:25:36.604 5527-5527/com.quickblox.q_municate W/System.err: com.quickblox.core.exception.QBResponseException: Incorrect url protocol
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.auth.session.Query.setUrl(Unknown Source)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.auth.session.Query.setupRequest(Unknown Source)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.auth.session.QueryCreateSession.setupRequest(Unknown Source)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.auth.session.Query.perform(Unknown Source)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.auth.session.Query.createSessionIfNeed(Unknown Source)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.auth.session.Query.perform(Unknown Source)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.extensions.PerformOnSubscribe.call(PerformOnSubscribe.java:31)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at com.quickblox.extensions.PerformOnSubscribe.call(PerformOnSubscribe.java:16)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10200)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
12-11 21:25:36.612 5527-5527/com.quickblox.q_municate W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10200)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-11 21:25:36.613 5527-5527/com.quickblox.q_municate D/BaseAuthActivity: onError Incorrect url protocol`

**Comment by tatanka987** [comment]
check build variant in Android Studio and check configs for this build variant in your gradle.properties file

**Comment by sami-abdul** [comment]
@tatanka987. It was already empty. Where can I find customApiEndPoint?

**Comment by tatanka987** [comment]
You can follow guide [How to run Q-municate with own endpoints](https://quickblox.com/developers/Q-municate#Q-municate_Android). If you followed this guide, just change build variant to 'standardDebug'.
