### ISSUE TITLE
What are the Maximum Number of Participants we can Add in Group Chat? 

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#262]
Hi,

I searched the document but could not find this thing. What are the Maximum Number of Participants we can Add in Group Chat? It will be grateful for help.

Thanks,
-Rashid

**Comment by tatanka987** [comment]
now this parameter is unlimited, but server team planed set limit to 30 occupants, I think you should develop your app with this fact in mind

**Comment by sheikhrashid** [comment]
I have Pro Membership of QuickBlox, 30 for me? or unlimited?

**Comment by tatanka987** [comment]
You use shared server, it means this config (30 users) for you too. Only clients who have own server (Enterprise plans) can config this parameter on own server.

**Comment by sheikhrashid** [comment]
I see. Thanks
