### ISSUE TITLE
Push Notification initilization

### ISSUE THREAD

**Issue by beytiii** [QuickBlox/q-municate-android#264]
Hi,
q-municate is really helpful to understand detail of Quickblox and its SDK.
But question appeared after integration of firebase with q-municate.
Firebase authentication via phone number is working but FCM isn't.
I followed the steps provided by your team. (copied sender_id, legacy server key into project; added dependencies firebase-messaging etc. (via Tools -> Firebase in Android Studio))
But notification is not working. How do I solve the issue? Is there any complete documentary or guide to add notifications in q-municate?

Thank you

**Comment by tatanka987** [comment]
you shouldn't add dependency to firebase-messaging if you don't need newest version of this lib (in latest version of QuickBlox Android SDK integrated version 11.4.2). If you made all needs from guide, try uninstall Q-municate and install it again. If issue will be actual again, provide there logs from starting your app to getting issue.
