### ISSUE TITLE
Getting incorrect url protocol toast message

### ISSUE THREAD

**Issue by karthiks2017** [QuickBlox/q-municate-android#266]
I ran the app and went past the phone signup. After receiving sms, the app goes back to previous screen and displays a toast _incorrect url protocol_
log output is here
`
12-20 16:00:12.118 16438-16438/com.quickblox.q_municate D/BaseActivity: onRestart
12-20 16:00:12.119 16438-17296/com.quickblox.q_municate V/FA: Activity paused, time: 34499899
12-20 16:00:12.122 16438-16438/com.quickblox.q_municate D/ActivityLifecycleHandler: onActivityStarted LandingActivity
12-20 16:00:12.122 16438-16438/com.quickblox.q_municate D/ActivityLifecycleHandler: onActivityStarted , chatDestroyed=false, numberOfActivitiesInForeground= 0
12-20 16:00:12.122 16438-16438/com.quickblox.q_municate D/BaseActivity: onStart
12-20 16:00:12.122 16438-16438/com.quickblox.q_municate D/BaseActivity: connectToService()
12-20 16:00:12.126 16438-16438/com.quickblox.q_municate V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{89c608d com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity,ident = 1}, this =com.android.internal.policy.PhoneWindow$DecorView{71fb43a V.E...... R.....ID 0,0-720,1280}
12-20 16:00:12.126 16438-16438/com.quickblox.q_municate D/ActivityThread: ACT-SHOW_WINDOW handled : 0 / android.os.BinderProxy@54eb90b
12-20 16:00:12.127 16438-17296/com.quickblox.q_municate D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=42485, firebase_screen_class(_sc)=PhoneVerificationActivity, firebase_screen_id(_si)=-5218459331218578135}]
12-20 16:00:12.136 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: beginTransaction()
12-20 16:00:12.139 16438-16438/com.quickblox.q_municate I/art: Rejecting re-init on previously-failed class java.lang.Class<com.firebase.ui.auth.provider.TwitterProvider>
12-20 16:00:12.140 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: endTransaction()
12-20 16:00:12.142 16438-16438/com.quickblox.q_municate D/ActivityThread: SEND_RESULT handled : 0 / ResultData{token=android.os.BinderProxy@5a447dd results[ResultInfo{who=null, request=65542, result=-1, data=Intent { (has extras) }}]}
12-20 16:00:12.142 16438-16438/com.quickblox.q_municate V/ActivityThread: Performing resume of ActivityRecord{8f4dfb4 token=android.os.BinderProxy@5a447dd {com.quickblox.q_municate/com.firebase.ui.auth.KickoffActivity}}
12-20 16:00:12.142 16438-16438/com.quickblox.q_municate V/ActivityThread: Resume ActivityRecord{8f4dfb4 token=android.os.BinderProxy@5a447dd {com.quickblox.q_municate/com.firebase.ui.auth.KickoffActivity}} started activity: true, hideForNow: true, finished: true
12-20 16:00:12.143 16438-16438/com.quickblox.q_municate V/ActivityThread: Scheduling idle handler for ActivityRecord{8f4dfb4 token=android.os.BinderProxy@5a447dd {com.quickblox.q_municate/com.firebase.ui.auth.KickoffActivity}}
12-20 16:00:12.144 16438-16438/com.quickblox.q_municate D/ActivityThread: ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@5a447dd
12-20 16:00:12.151 16438-16438/com.quickblox.q_municate D/Surface: Surface::allocateBuffers(this=0xb842e248)
12-20 16:00:12.151 16438-16753/com.quickblox.q_municate D/OpenGLRenderer: CanvasContext() 0xb8691198 initialize window=0xb842e250, title=com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity
12-20 16:00:12.151 16438-16753/com.quickblox.q_municate D/Surface: Surface::connect(this=0xb842e248,api=1)
12-20 16:00:12.153 16438-16753/com.quickblox.q_municate W/libEGL: [ANDROID_RECORDABLE] format: 1
12-20 16:00:12.156 16438-16753/com.quickblox.q_municate D/mali_winsys: new_window_surface returns 0x3000
12-20 16:00:12.178 16438-17296/com.quickblox.q_municate V/FA: Using measurement service
12-20 16:00:12.178 16438-17296/com.quickblox.q_municate V/FA: Connection attempt already in progress
12-20 16:00:12.180 16438-16438/com.quickblox.q_municate D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@cb4725d className=com.quickblox.q_municate_core.service.QBService packageName=com.quickblox.q_municate intent=null}
12-20 16:00:12.180 16438-16438/com.quickblox.q_municate D/QBService: onCreate()
12-20 16:00:12.181 16438-16438/com.quickblox.q_municate D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@cb4725d className=com.quickblox.q_municate_core.service.QBService packageName=com.quickblox.q_municate intent=null}
12-20 16:00:12.181 16438-16438/com.quickblox.q_municate V/ActivityThread: handleBindService s=com.quickblox.q_municate_core.service.QBService@f84f0a3 rebind=false
12-20 16:00:12.181 16438-16438/com.quickblox.q_municate D/QBService: onBind
12-20 16:00:12.182 16438-16438/com.quickblox.q_municate D/ActivityThread: SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@cb4725d intent=Intent { cmp=com.quickblox.q_municate/com.quickblox.q_municate_core.service.QBService }}
12-20 16:00:12.185 16438-16753/com.quickblox.q_municate D/OpenGLRenderer: ~CanvasContext() 0xb87f2b28
12-20 16:00:12.189 16438-16438/com.quickblox.q_municate D/ActivityThread: ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@5a447dd
12-20 16:00:12.190 16438-16438/com.quickblox.q_municate V/InputMethodManager: onWindowFocus: null softInputMode=32 first=true flags=#81810100
12-20 16:00:12.191 16438-16438/com.quickblox.q_municate V/InputMethodManager: START INPUT: com.android.internal.policy.PhoneWindow$DecorView{71fb43a V.E...... R.....ID 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@dfe4fa0 controlFlags=#104
12-20 16:00:12.207 16438-16753/com.quickblox.q_municate I/[MALI][Gralloc]: [+]r_hnd(0xb873ec58), client(67), share_fd(63)
12-20 16:00:12.207 16438-16753/com.quickblox.q_municate D/GraphicBuffer: register, handle(0xb873ec58) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
12-20 16:00:12.225 16438-16753/com.quickblox.q_municate I/[MALI][Gralloc]: [+]r_hnd(0xb8807f48), client(67), share_fd(72)
12-20 16:00:12.225 16438-16753/com.quickblox.q_municate D/GraphicBuffer: register, handle(0xb8807f48) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
12-20 16:00:12.230 16438-16438/com.quickblox.q_municate D/BaseActivity: onServiceConnected
12-20 16:00:12.230 16438-17296/com.quickblox.q_municate D/FA: Connected to remote service
12-20 16:00:12.230 16438-17296/com.quickblox.q_municate V/FA: Processing queued up service tasks: 2
12-20 16:00:12.230 16438-16438/com.quickblox.q_municate D/BaseActivity: onActivityResult
12-20 16:00:12.230 16438-16438/com.quickblox.q_municate D/BaseAuthActivity: onActivityResult, result code = 456
12-20 16:00:12.238 16438-16438/com.quickblox.q_municate D/ActivityThread: SEND_RESULT handled : 0 / ResultData{token=android.os.BinderProxy@54eb90b results[ResultInfo{who=null, request=456, result=-1, data=Intent { (has extras) }}]}
12-20 16:00:12.238 16438-16438/com.quickblox.q_municate V/ActivityThread: Performing resume of ActivityRecord{b56c0da token=android.os.BinderProxy@54eb90b {com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity}}
12-20 16:00:12.239 16438-16438/com.quickblox.q_municate D/ActivityLifecycleHandler: onActivityResumed LandingActivity count of activities = 0
12-20 16:00:12.239 16438-16438/com.quickblox.q_municate D/BaseActivity: onResume
12-20 16:00:12.239 16438-16438/com.quickblox.q_municate V/BaseActivity: registerBroadcastReceivers()
12-20 16:00:12.240 16438-16438/com.quickblox.q_municate V/BaseActivity: addActions()
12-20 16:00:12.243 16438-16438/com.quickblox.q_municate D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{b56c0da token=android.os.BinderProxy@54eb90b {com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity}}
12-20 16:00:12.243 16438-16438/com.quickblox.q_municate V/ActivityThread: Resume ActivityRecord{b56c0da token=android.os.BinderProxy@54eb90b {com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity}} started activity: false, hideForNow: false, finished: false
12-20 16:00:12.243 16438-16438/com.quickblox.q_municate V/ActivityThread: Resuming ActivityRecord{b56c0da token=android.os.BinderProxy@54eb90b {com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity}} with isForward=false
12-20 16:00:12.243 16438-16438/com.quickblox.q_municate V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{89c608d com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity,ident = 1}, this =com.android.internal.policy.PhoneWindow$DecorView{71fb43a V.E...... R....... 0,0-720,1280}
12-20 16:00:12.243 16438-16438/com.quickblox.q_municate V/ActivityThread: Scheduling idle handler for ActivityRecord{b56c0da token=android.os.BinderProxy@54eb90b {com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.LandingActivity}}
12-20 16:00:12.244 16438-16438/com.quickblox.q_municate D/ActivityThread: ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@54eb90b
12-20 16:00:12.245 16438-16438/com.quickblox.q_municate V/FirebaseAuthHelper: Token got successfully. TOKEN = eyJhbGciOiJSUzI1NiIsImtpZCI6IjIxYjE2MzM1ODU0NTYyMDAxZGM0ODUxZGRlYTU0ZWUzYThiYTg1YmMifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHJvdmVuLWNhdGNoZXItMTg5NTEwIiwiYXVkIjoicHJvdmVuLWNhdGNoZXItMTg5NTEwIiwiYXV0aF90aW1lIjoxNTEzNzY1ODEwLCJ1c2VyX2lkIjoiTEw2ZUo0VUNtMmhUWTFoejhXblBHakhwRmVsMiIsInN1YiI6IkxMNmVKNFVDbTJoVFkxaHo4V25QR2pIcEZlbDIiLCJpYXQiOjE1MTM3NjU4MTAsImV4cCI6MTUxMzc2OTQxMCwicGhvbmVfbnVtYmVyIjoiKzkxOTE0NTY3NjE0NyIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsicGhvbmUiOlsiKzkxOTE0NTY3NjE0NyJdfSwic2lnbl9pbl9wcm92aWRlciI6InBob25lIn19.eB_F1251Fuch_gLYobHwcz_duJnzBudXWz-VitoR0BD1htB4wehwAyb4i7zQzPLAeoO6jp9Iaz0gS3HeRzkwz5WSFxzg-jifehsTBrkcn4OJp3nZiKlroHbouweAa3I8jKhRIAjfJvM2ZZl-uFLSTuz0c5wRMZhuYyb8sK9UyX-6DfDLk94uZEYfo9ciFBG8EBsMbzv__4AZZZI8pL29b5mBhQnR6KdNei65Mx1KAl1x1SE9XGhpOVkbkaaExTnZigyqp1_wHxXVDeZysOvMbTnjNhZfFJWMip6wOu2GVwKwGIcEf0yQnMdFPlhSRipjJtGMfk8GKK0OdFcmRp_75w
12-20 16:00:12.248 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: beginTransaction()
12-20 16:00:12.251 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: endTransaction()
12-20 16:00:12.261 16438-17296/com.quickblox.q_municate V/FA: Activity resumed, time: 34500036
12-20 16:00:12.264 16438-16438/com.quickblox.q_municate D/BaseAuthActivity: FirebaseAuthCallback onSuccess()
12-20 16:00:12.272 16438-17296/com.quickblox.q_municate D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=PhoneVerificationActivity, firebase_previous_id(_pi)=-5218459331218578135, firebase_screen_class(_sc)=LandingActivity, firebase_screen_id(_si)=-5218459331218578137}]
12-20 16:00:12.279 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: beginTransaction()
12-20 16:00:12.281 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: endTransaction()
12-20 16:00:12.310 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: beginTransaction()
12-20 16:00:12.313 16438-17296/com.quickblox.q_municate D/SQLiteDatabase: endTransaction()
12-20 16:00:12.428 16438-16753/com.quickblox.q_municate D/Surface: Surface::disconnect(this=0xb8743328,api=1)
12-20 16:00:12.434 16438-16753/com.quickblox.q_municate D/GraphicBuffer: unregister, handle(0xb8769590) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
12-20 16:00:12.434 16438-16753/com.quickblox.q_municate I/[MALI][Gralloc]: [-]r_hnd(0xb8769590), client(67), share_fd(71)
12-20 16:00:12.435 16438-16753/com.quickblox.q_municate D/GraphicBuffer: unregister, handle(0xb8779ba8) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
12-20 16:00:12.436 16438-16753/com.quickblox.q_municate I/[MALI][Gralloc]: [-]r_hnd(0xb8779ba8), client(67), share_fd(73)
12-20 16:00:12.436 16438-16753/com.quickblox.q_municate E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb8763728
12-20 16:00:12.436 16438-16753/com.quickblox.q_municate D/mali_winsys: [MALI] win=0xb8743330, native_buffer=0xb875d208, fd=-1
12-20 16:00:12.436 16438-16753/com.quickblox.q_municate D/GraphicBuffer: unregister, handle(0xb8763728) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
12-20 16:00:12.437 16438-16753/com.quickblox.q_municate I/[MALI][Gralloc]: [-]r_hnd(0xb8763728), client(67), share_fd(74)
12-20 16:00:12.437 16438-16753/com.quickblox.q_municate D/Surface: Surface::disconnect(this=0xb8743328,api=1)
12-20 16:00:12.448 16438-17303/com.quickblox.q_municate D/QBASDK: Error occurred while parsing url :Protocol not found: /session.json
12-20 16:00:12.448 16438-17303/com.quickblox.q_municate D/QBASDK: Incorrect url protocol
12-20 16:00:12.449 16438-17303/com.quickblox.q_municate D/QBASDK: error result class rx.internal.operators.OnSubscribeMap$MapSubscriber
12-20 16:00:12.449 16438-17303/com.quickblox.q_municate D/QBASDK: PerformOnSubscribe:processOnError 
12-20 16:00:12.468 16438-16438/com.quickblox.q_municate D/BaseActivity: onAttachFragment
`

**Comment by tatanka987** [comment]
please follow recommendations for [this issue](https://github.com/QuickBlox/q-municate-android/issues/261) #261

**Comment by karthiks2017** [comment]
Changing build variant to standardDebug worked. Thank you.
