### ISSUE TITLE
How to change the package id?

### ISSUE THREAD

**Issue by martyndix** [QuickBlox/q-municate-android#268]
Hi all,
How do you change the package="com.quickblox.q_municate" to something else? I have changed the value here in AndroidManifest.xml but I am sure there are references to change elsewhere. Please can someone tell me where they are and what to change?
Thanks,
Martyn.

**Comment by sheikhrashid** [comment]
Right click on the Package Name. Go to **Refactor -> Rename**. Enter your package name and Click Ok. you are done.

**Comment by AbdaalRuhaani** [comment]
sometimes Refactor does not work in Android Studio so I just Simply Downloaded notepad++ and Searched com.quickblox.q_municate in whole project and replace it mine ex.  "com.mycompany.myapp" I hope it also works for you :)

**Comment by sheikhrashid** [comment]
i have done that. Thanks
