### ISSUE TITLE
Why Not Getting QMUser?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#270]
**QMUserService.getInstance().getUserCache().get((long)userId);**

This was working fine. Suddenly it has stopped working and it is returning null. 
Please help me out.

**Comment by tatanka987** [comment]
Try search changes in your code to localize this issue, in current Q-municate version it works fine. Maybe your cache don't contains user with this id or other ways.

**Comment by sheikhrashid** [comment]
It doesn't works first time as there is no cache there. By the way I have solved that by getting QMUser fro different method.
