### ISSUE TITLE
How can we Get All Users from Quickblox?

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#271]
I am using Q-municate Android Project.

I am stuck at an issue. I can't get all users at once from Quickblox. It only allows me to get users **at most 100** in one server hit. I have seen the method on official docs of **how to get all users**, but that is using **recursion** and  I have more than 5000+ users. It is making the whole thing extremely slow.

A big problem. Sorry to say, but its not a good method to get all users.

Is there any other way, we can **Get All Users?**

**Comment by tatanka987** [comment]
It is common practice, because not all users want get all friends at once. QuckBlox provides possibility to change this parameter for your needs if you use Enterprise account (with own server). More about plans [there](https://quickblox.com/plans/).

**Comment by sheikhrashid** [comment]
We are using Pro Plan. Can we have this in Pro Plan?

**Comment by tatanka987** [comment]
no, you can't use it in your current plan

**Comment by sheikhrashid** [comment]
Please confirm, if we use Enterprise Plan, can we get the Quickblox users quickly?

Please confirm this, so we can buy the plan

**Comment by tatanka987** [comment]
Sorry, but I don't know all specifics for Enterprise clients, you can contact to our sales team to get more information about advantages for different plans filling this form https://quickblox.com/enterprise/ If you want faster response send your e-mail address to my e-mail valentyn.tereshchenko@injoit.com and our sales manager will contact with you as soon as possible.

**Comment by sheikhrashid** [comment]
okay thanks
