### ISSUE TITLE
"Empty address book" error in registeredUsersFromAddressBookWithUdid

### ISSUE THREAD

**Issue by sheikhrashid** [QuickBlox/q-municate-android#272]
**"Empty address book"** error in **registeredUsersFromAddressBookWithUdid**

What does it mean?

Address book is already uploaded using **uploadAddressBookWithUdid** method.

**Comment by tatanka987** [comment]
Looks like you don't have users which registered on QB from your address book. If you want just load uploaded address book use QBUsers.getAddressBook(udid).perfom().

**Comment by sheikhrashid** [comment]
is it necessary for this method to Register via Phone?

**Comment by tatanka987** [comment]
It is not necessary, but user should have phone number from your address book.

**Comment by sheikhrashid** [comment]
yes it has in **Phone** field of **QBuser**

**Comment by tatanka987** [comment]
Are you sure that user's phone number is the same with address book? additionally check udid for uploaded address book and for downloading users.
