### ISSUE TITLE
Missing callback for confirmation of "subscriptionRequest" (QBSubscriptionListener Interface)

### ISSUE THREAD

**Issue by prographo** [QuickBlox/q-municate-android#273]
For QBRoster.SubscriptionMode.mutual, should be a call back in QBSubscriptionListener for when app gets chatRoster.confirmSubscription message. Otherwise how / where is it processed? Something like;
```
private class SubscriptionListener implements QBSubscriptionListener {

        @Override
        public void subscriptionRequested(int userId) {
          // received subscription request
        }

        **@Override
        public void subscriptionRequestedConfirmed(int userId) {
          // received confirmation of subscription request
        }**
    }
```
iOS has chatDidReceiveAcceptContactRequestFromUser.

**Comment by RomanPronin** [comment]
Hi, subscriptionRequested() means some user received the request to be added to the contact list. For confirmation about subscription state there is QBRosterListener with entriesUpdated(), which called when a roster entries are updated. Look at its [implementation in Q-mun](https://github.com/QuickBlox/q-municate-android/blob/c6539ceb8abcb090005ddfbc59e03470d49dfd3a/Q-municate_core/src/main/java/com/quickblox/q_municate_core/qb/helpers/QBFriendListHelper.java#L402) for details.
