### ISSUE TITLE
RuntimeException: Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by Pushpganga25** [QuickBlox/q-municate-android#276]
Process: com.quickblox.q_municate, PID: 7611
                  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.quickblox.q_municate/com.quickblox.q_municate.ui.activities.authorization.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "com.quickblox.q_municate.ui.activities.authorization.SplashActivity" on path: DexPathList[[zip file "/data/app/com.quickblox.q_municate-1/base.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.quickblox.q_municate-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.quickblox.q_municate-1/lib/arm64, /data/app/com.quickblox.q_municate-1/base.apk!/lib/arm64-v8a, /data/app/com.quickblox.q_municate-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.quickblox.q_municate-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a

**Comment by Pushpganga25** [comment]
I only add app_id,auth_key, auth_secret ,api_endpoint, chat_endpoint, account_key  and then firebase
_auth _project_id,facebook_app_id and sender id

**Comment by Pushpganga25** [comment]
plz... reply me

**Comment by tatanka987** [comment]
@Pushpganga25 which IDE do you use for development? Please provide steps to reproduce this issue.

**Comment by Pushpganga25** [comment]
I use IDE android studio 3.0.1. Thanks.....

**Comment by tatanka987** [comment]
this is strange error, we can't reproduce it on our side, try next to fix it:
- check path to SplashActivity in AndroidManifest.xml (if you changed packet name);
- delete 'build' directories and rebuild your project again;
- disable Instant Run, clean project and rebuild it again;

**Comment by Pushpganga25** [comment]
Error:(146, 0) Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=devDebug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.
<a href="openFile:E:\AndroidProject\1march\q-municate-android-master\Q-municate_app\build.gradle">Open File</a> 


Now i gate this error

**Comment by tatanka987** [comment]
looks like you updated gradle plugin for this project (you didn't write about this before). To fix it use next code:
```
newApkName = "some_apk_name"
output.outputFileName = newApkName
```
