### ISSUE TITLE
Error when build this project --> No Such property : parent for class: java.lang.String

### ISSUE THREAD

**Issue by andhicapratama** [QuickBlox/q-municate-android#277]
Error:(158, 0) No such property: parent for class: java.lang.String
<a href="openFile:C:\Users\T430\Documents\AndroidStudioProjects\q-municate-android-master\Q-municate_app\build.gradle">Open File</a>

this error refers to this code:

def changeApkFileName(variant) {
    variant.outputs.each { output ->
        def file = output.outputFileName
        def newName = 'QMUN_Android_v.' + rootProject.versionName + '_c.' + rootProject.versionCode + '-' + variant.buildType.name + '.apk'
        output.outputFileName = new File(file.parent, newName)
    }
}

How can i fix this

**Comment by tatanka987** [comment]
use ```output.outputFileName = newName``` instead of ```output.outputFileName = new File(file.parent, newName)```
