### ISSUE TITLE
Push notification issue

### ISSUE THREAD

**Issue by robi10101298** [QuickBlox/q-municate-android#29]
When I open the app, he sends me a push notification: ,,You've lost a message". Resolve this pls

**Comment by katiatereshchenkova** [comment]
Can you describe this issue more detailed?
Is it the first time you open the app or maybe it happens after relogin in the app
Also, сould you please provide a logs for us?

**Comment by robi10101298** [comment]
When I relogin, and on some devices, when I start the app for the first time

**Comment by katiatereshchenkova** [comment]
Could you provide a logs for us, please?

**Comment by robi10101298** [comment]
07-27 20:10:18.620  20330-20330/com.quickblox.q_municate I/art﹕ Late-enabling -Xcheck:jni
07-27 20:10:19.505  20330-20330/com.quickblox.q_municate D/ImageLoader﹕ Initialize ImageLoader with configuration
07-27 20:10:19.618  20330-20330/com.quickblox.q_municate D/ContextHelper﹕ convertTheme. context->name=com.quickblox.q_municate themeResourceId=2131492869
07-27 20:10:19.741  20330-20330/com.quickblox.q_municate I/Crashlytics﹕ Initializing Crashlytics 1.1.13.29
07-27 20:10:19.750  20330-20345/com.quickblox.q_municate I/art﹕ CheckpointMarkThreadRoots callback created = 0xaaf3a280
07-27 20:10:19.801  20330-20345/com.quickblox.q_municate I/art﹕ CheckpointMarkThreadRoots callback created = 0xaaf3a250
07-27 20:10:19.836  20330-20345/com.quickblox.q_municate W/art﹕ Suspending all threads took: 8.634ms
07-27 20:10:19.856  20330-20345/com.quickblox.q_municate I/art﹕ Background partial concurrent mark sweep GC freed 13486(737KB) AllocSpace objects, 10(400KB) LOS objects, 40% free, 10MB/16MB, paused 15.668ms total 106.651ms
07-27 20:10:19.860  20330-20330/com.quickblox.q_municate I/Timeline﹕ Timeline: Activity_launch_request id:com.quickblox.q_municate time:719402
07-27 20:10:19.972  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
07-27 20:10:19.972  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
07-27 20:10:19.973  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
07-27 20:10:19.973  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=1024; ai_family=0
07-27 20:10:19.996  20330-20416/com.quickblox.q_municate I/System.out﹕ propertyValue:false
07-27 20:10:20.031  20330-20330/com.quickblox.q_municate D/ContextHelper﹕ convertTheme. context->name=com.quickblox.q_municate themeResourceId=2131492869
07-27 20:10:20.101  20330-20330/com.quickblox.q_municate D/QBASDK﹕ onActivityResumed0
07-27 20:10:20.123  20330-20330/com.quickblox.q_municate I/Activity﹕ Activity.onPostResume() called
07-27 20:10:20.147  20330-20429/com.quickblox.q_municate D/OpenGLRenderer﹕ Render dirty regions requested: true
07-27 20:10:20.169  20330-20429/com.quickblox.q_municate I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
    OpenGL ES Shader Compiler Version: E031.25.03.00
    Build Date: 03/02/15 Mon
    Local Branch: LA.BF.1.1.2_RB1-AU017-20150302-1163306-1163307-1163308-1163309
    Remote Branch:
    Local Patches:
    Reconstruct Branch:
07-27 20:10:20.181  20330-20429/com.quickblox.q_municate I/OpenGLRenderer﹕ Initialized EGL, version 1.4
07-27 20:10:20.270  20330-20429/com.quickblox.q_municate D/OpenGLRenderer﹕ Enabling debug mode 0
07-27 20:10:20.289  20330-20330/com.quickblox.q_municate D/Atlas﹕ Validating map...
07-27 20:10:20.315  20330-20330/com.quickblox.q_municate D/CALL_INTEGRATION﹕ construct  QBVideoChatHelper
07-27 20:10:20.333  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ START connectivity manager
07-27 20:10:20.333  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Init broadcastreceiver
07-27 20:10:20.395  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Receive connectivity change
07-27 20:10:20.396  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Check does connectivity equal mobile or wifi types
07-27 20:10:20.397  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Connectivity is true current is true
07-27 20:10:20.397  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Receive wifi change
07-27 20:10:20.398  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Wifi state is Bundle[{previous_wifi_state=1, wifi_state=3}]
07-27 20:10:20.399  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Wifi state is 1
07-27 20:10:20.399  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Set connectivity state
07-27 20:10:20.399  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Notify about  connectivity state
07-27 20:10:20.399  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ onConnectionChange in BaseActivity
07-27 20:10:20.399  20330-20330/com.quickblox.q_municate D/Fixes CONNECTIVITY﹕ Connection is false
07-27 20:10:20.848  20330-20330/com.quickblox.q_municate I/art﹕ Thread[1,tid=20330,WaitingForJniOnLoad,Thread*=0xb4827800,peer=0x74ba91f8,"main"] recursive attempt to load library "/system/lib/libhook_jni.so"
07-27 20:10:20.881  20330-20330/com.quickblox.q_municate E/MediaProfilesEx-JNI﹕ register_com_lge_media_MediaProfilesEx
07-27 20:10:20.881  20330-20330/com.quickblox.q_municate E/MediaRecorderEx-JNI﹕ register_com_lge_media_MediaRecorderEx
07-27 20:10:20.885  20330-20330/com.quickblox.q_municate D/AudioSystemEx﹕ register_com_lge_media_LGAudioSystem
07-27 20:10:20.885  20330-20330/com.quickblox.q_municate E/SurfaceControlEx﹕ register_com_lge_view_SurfaceControlEx
07-27 20:10:20.887  20330-20330/com.quickblox.q_municate I/art﹕ Thread[1,tid=20330,WaitingForJniOnLoad,Thread*=0xb4827800,peer=0x74ba91f8,"main"] recursive attempt to load library "/system/lib/libhook_jni.so"
07-27 20:10:20.887  20330-20330/com.quickblox.q_municate D/LGMtpDatabaseJNI﹕ register_android_mtp_LGMtpDatabase
07-27 20:10:20.888  20330-20330/com.quickblox.q_municate I/art﹕ Thread[1,tid=20330,WaitingForJniOnLoad,Thread*=0xb4827800,peer=0x74ba91f8,"main"] recursive attempt to load library "/system/lib/libhook_jni.so"
07-27 20:10:20.891  20330-20330/com.quickblox.q_municate D/LGMtpServerJNI﹕ register_android_mtp_LGMtpServer
07-27 20:10:20.892  20330-20330/com.quickblox.q_municate I/art﹕ Thread[1,tid=20330,WaitingForJniOnLoad,Thread*=0xb4827800,peer=0x74ba91f8,"main"] recursive attempt to load library "/system/lib/libhook_jni.so"
07-27 20:10:20.892  20330-20330/com.quickblox.q_municate E/MediaPlayerEx-jni﹕ register_com_lge_view_MediaPlayerEx
07-27 20:10:20.899  20330-20330/com.quickblox.q_municate I/art﹕ Thread[1,tid=20330,WaitingForJniOnLoad,Thread*=0xb4827800,peer=0x74ba91f8,"main"] recursive attempt to load library "/system/lib/libhook_jni.so"
07-27 20:10:20.901  20330-20330/com.quickblox.q_municate D/﹕ register_com_lge_emoji_EmojiUtil
07-27 20:10:20.974  20330-20330/com.quickblox.q_municate I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1a4fe81e time:720516
07-27 20:10:21.402  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
07-27 20:10:21.403  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
07-27 20:10:21.403  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
07-27 20:10:21.403  20330-20416/com.quickblox.q_municate D/libc-netbsd﹕ [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=1024; ai_family=0
07-27 20:10:21.507  20330-20416/com.quickblox.q_municate I/System.out﹕ propertyValue:false
07-27 20:10:24.988  20330-20330/com.quickblox.q_municate I/Notification﹕ GcmBroadcastReceiver. Is push notification forbidden false
07-27 20:10:25.017  20330-20330/com.quickblox.q_municate E/BroadcastReceiver﹕ BroadcastReceiver trying to return result during a non-ordered broadcast
    java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast
            at android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:785)
            at android.content.BroadcastReceiver.setResultCode(BroadcastReceiver.java:551)
            at com.quickblox.q_municate.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:32)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2663)
            at android.app.ActivityThread.access$1700(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5376)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
07-27 20:10:25.027  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ createPushEvent
07-27 20:10:25.046  20330-20340/com.quickblox.q_municate W/art﹕ Suspending all threads took: 17.559ms
07-27 20:10:25.049  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ Start parse message
07-27 20:10:25.049  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ sendNotification method called
07-27 20:10:25.088  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ Opening dialog data saved
07-27 20:10:25.112  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ PendingIntent for notification is created
07-27 20:10:25.156  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ Notification is built
07-27 20:10:25.172  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ Call notify
07-27 20:10:25.173  20330-20706/com.quickblox.q_municate D/Fixes Notification﹕ completeWakefulIntent called
