### ISSUE TITLE
chatRoster state / subscription request lost if app not running

### ISSUE THREAD

**Issue by prographo** [QuickBlox/q-municate-android#290]
If subscription request is sent from user A to user B while B is offline (phone is off), then that request is lost.

Everything works if the app is in a background state, but if the app is not running, then the request is lost.

**Comment by prographo** [comment]
subscription request confirmations are also thrown away if the user is offline.

**Comment by RomanPronin** [comment]
In Qmun used logic with PROPERTY_NOTIFICATION_TYPE with FRIENDS_REQUEST value for chat message. Just look at [code](https://github.com/QuickBlox/q-municate-android/blob/370ae97aabb64f733c798169f161afc6ce091d1b/Q-municate_core/src/main/java/com/quickblox/q_municate_core/qb/helpers/QBFriendListHelper.java#L143-L143) and explore it.
