### ISSUE TITLE
Cannot set the value of read-only property 'outputFile'

### ISSUE THREAD

**Issue by jmfranci** [QuickBlox/q-municate-android#292]
Error:(158, 0) Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=standardDebug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

**Comment by RomanPronin** [comment]
Related to https://github.com/QuickBlox/q-municate-android/issues/276
