### ISSUE TITLE
How can i pass one more parameter with message in chat dialog?

### ISSUE THREAD

**Issue by tatveshwebmigrates** [QuickBlox/q-municate-android#293]
how can i send custom parameter with message and how can i edit QBChatMessage.java default class in android demo.

QBChatMessage chatMessage = new QBChatMessage();
        chatMessage.setBody(body);
        chatMessage.setProperty(ChatNotificationUtils.PROPERTY_DATE_SENT, String.valueOf(time));

i want to send one more parameter with   ->  chatMessage.setCustomparameter("Some String");
how it is possible?

**Comment by tatveshwebmigrates** [comment]
hello????

**Comment by RomanPronin** [comment]
Hi, as states in [docs](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Use_custom_parameters_in_a_message) you can use custom parameters for the messages you send in the chat:
`chatMessage.setProperty("name", "Bob");
chatMessage.setProperty("age", "25");`
