### ISSUE TITLE
Image not getting displayed while sent from WEB to ANDROID

### ISSUE THREAD

**Issue by meetVora1994** [QuickBlox/q-municate-android#294]
I'm trying to send image from Q-Municate-WEB version to Q-Municate-Android.
The image is not getting displayed on Android device. But I checked this with iPhone version, it is displaying image fine.

In more detail, whenever I send the image from WEB version, the empty box with loading appears for half or less second, then that box gets disappear. Everything (except image) working fine, like text messages working fine. The problem occurs only one way: WEB to ANDROID (specially for image sending scenario).

Q-Municate-WEB version used: 1.4.3
Q-Municate-ANDROID version used: [versionName = '2.6'; versionCode = 260] [took latest code from GitHub | on 10 April 2018]

**Comment by RomanPronin** [comment]
Our tester checked this case, and it is all ok. So, did you change anything in project, maybe even some small changes?
