### ISSUE TITLE
getting implementation trouble on android app

### ISSUE THREAD

**Issue by Vivekmalani** [QuickBlox/q-municate-android#297]
when i am adding all those dependencies 

compile project(':q-municate_auth_service')
compile project(':q-municate_base_cache')
compile project(':q-municate_base_service')
compile project(':Q-municate_core')
compile project(':Q-municate_db')
compile project(':q-municate_user_cache')
compile project(':q-municate_user_service')

it is not working for me

can someone help me from starting, how can i configure it for my android app.

**Comment by RomanPronin** [comment]
You may have a look at official Q-mun [docs](https://quickblox.com/developers/Q-municate#Q-municate_Android). You'll find a guidance how to run project Q-municate with your own QuickBlox endpoints.
