### ISSUE TITLE
Background call issue

### ISSUE THREAD

**Issue by starlucas629** [QuickBlox/q-municate-android#300]
I built iOS and android video call app using quickblox webRTC.
I used Q-municate.
It has all functions.
Background call runs well in iphone to iphone, and android to android.
But iphone->android, android->iphone background call don't run at all.
Push notification runs well in all platforms.
I hope to get correct answer as soon as.
Thanks

**Comment by starlucas629** [comment]
?

**Comment by RomanPronin** [comment]
@starlucas629, what version of Q-mun do you use?

**Comment by starlucas629** [comment]
I used last version in github

**Comment by RomanPronin** [comment]
You state you use latest version 2.7 from Goole Play market, and there are no background calls between iOS - Android?

**Comment by starlucas629** [comment]
Yes.

**Comment by RomanPronin** [comment]
It is not true. Background calls work fine, our testers have just tested this and it's all ok.

**Comment by starlucas629** [comment]
I only changed quickblox account keys, and firebase sender id.
buildTypes {
        release {
            minifyEnabled false
            debuggable false
            ext.enableCrashlytics = true
            signingConfig signingConfigs.release
            buildConfigField "String", "APP_ID", "\"70164\""
            buildConfigField "String", "AUTH_KEY", "\"65Re2y7gEG2jus6\""
            buildConfigField "String", "AUTH_SECRET", "\"FzGhdxZma9cPwE6\""
            buildConfigField "String", "API_ENDPOINT", "\"https://api.quickblox.com\""
            buildConfigField "String", "CHAT_ENDPOINT", "\"chat.quickblox.com\""
            buildConfigField "String", "ACCOUNT_KEY", "\"SX9yCWuaQsCJ7RUDkiru\""
            buildConfigField "String", "FIREBASE_AUTH_PROJECT_ID", devFirebaseAuthProjectId
            resValue "string", "facebookAppId", prodFacebookAppID
            resValue "string", "sender_id", "\"998226485013\""
            manifestPlaceholders = [fabricApiKey:prodFabricApiKey]
        }

        debug {
            debuggable true
            versionNameSuffix ' (debug)'
        }
    }

**Comment by starlucas629** [comment]
Background call runs well in same platforms.
But it doesn't run between iphone and android.

**Comment by RomanPronin** [comment]
Do push messages work between platforms?

**Comment by starlucas629** [comment]
No, It doesn't work too

**Comment by starlucas629** [comment]
After I call from iphone  to android (android is in background mode), if i open android app, I can see push alert.
Dose the push notification run?

**Comment by starlucas629** [comment]
I already checked all doc.
I think my Quickblox account has issue.
It is free account.
May be can I use paid account?
Thanks.

**Comment by starlucas629** [comment]
If I use paid account, can I solve this issue?

**Comment by RomanPronin** [comment]
I think you can resolve issue on your current account, but sure you can use paid account and get more privileges.

**Comment by starlucas629** [comment]
means?
Now can I solve this issue in free account?

**Comment by starlucas629** [comment]
Please let me know what should I change in the github code.

**Comment by RomanPronin** [comment]
All you need to change is stated in the doc. So, I want to clarify, is cross-platform messaging working? Does offline notification come on Android (on android side app is not running), when you send chat message from iOS? And from Android? Also, attach your project build.gradle file.
