### ISSUE TITLE
How can i Delete message in chat Dialog into Local Storage Android????

### ISSUE THREAD

**Issue by tatveshwebmigrates** [QuickBlox/q-municate-android#302]
how can i delete message permanently in 1 to 1 chat  android q-municate demo into local storage???

**Comment by tatveshwebmigrates** [comment]
Reply plz......

**Comment by tatveshwebmigrates** [comment]
??????

**Comment by tatveshwebmigrates** [comment]
hello anyone is there?

**Comment by tatveshwebmigrates** [comment]
Hello Reply Plz!!!

**Comment by AAPBD** [comment]
Well, got the code working finally. Also you have to delete the message from the LOCAL DB as well

**Comment by leena12345** [comment]
Please tell me how you delete it from local db?
