### ISSUE TITLE
Sdk Upgrade 2.x.x to 3.8.1 causing error with RTCGLVideoView missing VideoRendererGui

### ISSUE THREAD

**Issue by AbdaalRuhaani** [QuickBlox/q-municate-android#309]
`could not find class org.webrtc.VideoRendererGui.
`
**Kindly Tell me how Can I resolve it or Someone faced this yet and fixed so please link an Answer **
Thanks in Advance :)

**Comment by hedinGood** [comment]
I have the same problem!
