### ISSUE TITLE
Not getting call(Audio/Video) from android to iPhone when app is in background and vice versa.

### ISSUE THREAD

**Issue by brijeshwebmigrates** [QuickBlox/q-municate-android#311]
I am doing call from Android phone to iPhone but not getting call when iPhone app is in background. It is working fine when app is in foreground.

                try {
                         QBPushNotifications.createEvent(pushEvent).perform();
                         Log.e("pusheventsuccess", "success");
               } catch (QBResponseException e) {
                         Log.e("pusheventsuccess", "fail"+e.toString());
               }

Actually when i call and if iPhone app is in background then every time it is giving me this error in catch block.

 **Error => quickblox.core.exception.QBResponseException: No one can receive the message**

This is also same for iPhone to android. When iPhone app is calling to android user and if app is in background then i am not getting any notification or event.

Can you please suggest me how can i solve this.

**Comment by agchaniyara** [comment]
@WebmigratesCompany 

Have you got any solution for this?

**Comment by WebmigratesCompany** [comment]
No

**Comment by silicus-kirankhalkar** [comment]
@WebmigratesCompany - Have you resolved this issue?
