### ISSUE TITLE
Freinds List And Names from phone contacts like Whatsapp

### ISSUE THREAD

**Issue by Bosa17** [QuickBlox/q-municate-android#312]
Hello,
I want to have whatsapp like feature in my app. i Want to get the friend name and list from phone contacts and added to a users freind table as the new user signs up. I want them to add them automatically to their contact's New Message Activity , available to start a private Dialog.

Please Reply Soon.

**Comment by Bosa17** [comment]
Is anyone there?

**Comment by AyushiBShah** [comment]
https://github.com/QuickBlox/q-municate-android/issues/287
https://github.com/QuickBlox/q-municate-android/issues/267

Above two threads might be helpful to you.

**Comment by Bosa17** [comment]
I have read them but my problem remains...Can you please give a brief explanation how opponents appear in the chat list and how Friend works in general, so that I can manipulate it to my wish.

**Comment by Bosa17** [comment]
For Firebase users (using phone verification), how friends are added to the roster?

**Comment by Bosa17** [comment]
Anyone Please Reply
