### ISSUE TITLE
Groups created by the developer

### ISSUE THREAD

**Issue by robi10101298** [QuickBlox/q-municate-android#34]
Hi! How can I create some groups that can be seen by the users when they open the app? I think it's a major feature that needs to be implemented. Sorry because I wrote on the issues tab, but, unfortunately, GitHub doesn't have a ,,improvements and other stuffs" tab...

**Comment by soulfly** [comment]
It's possible to create public group chats

http://quickblox.com/developers/Android_XMPP_Chat_Sample#Create_new_group_chat_dialog

QBDialogType.GROUP_PUBLIC

**Comment by robi10101298** [comment]
Thanks for the tutorial! I ll try to create groups with specific names, where the users can join in it
