### ISSUE TITLE
Connect with Facebook Button

### ISSUE THREAD

**Issue by dnyasae** [QuickBlox/q-municate-android#40]
I cannot seem to sign in with the Facebook button. I created a Facebook app and changed the ApplicationID in my project. I got some invalid hash key errors which I fixed but I still cannot get this work. Is there anything else I need to be doing? Please help. Thanks

**Comment by Lordonnance** [comment]
Hey I'm joining you on this, thrying to connect Q-municate with another facebook app (another Quickblox app set up with the new facebook app credentials from the backend)

I still got the status 422 from login.json
[10-23 18:45:46.455: D/QBASDK(12614):     '{"errors":{"base":["Login or email required"]}}']

Here is the request :
POST https://api.quickblox.com/login.json?provider=facebook&keys[token]=CAAHv...ZDZD

Anyone with a solution ? Thanks

**Comment by dnyasae** [comment]
I get the exact same error as you below. I know the permissions for email request are not being sent. How do you ask for email as well and where do you place the code? Only public profile is being returned from Facebook which is the default. I have tried to set email permission but have not been successful. This is the problem and a solution would be great.
 *** RESPONSE *** 8c294e4a-4329-49dd-a616-89b43514d400 ***
    STATUS : 422
    HEADERS
    Access-Control-Allow-Origin=*
    Cache-Control=no-cache
    Connection=keep-alive
    Content-Length=47
    Content-Type=application/json; charset=utf-8
    Date=Wed, 30 Sep 2015 02:13:49 GMT
    QB-Token-ExpirationDate=2015-09-30 04:13:48 UTC
    QuickBlox-REST-API-Version=0.1.1
    Server=nginx/1.6.2
    Status=422 Unprocessable Entity
    X-Rack-Cache=invalidate, pass
    X-Request-Id=ad5f6fed90aa48578132858700d4af2e
    X-Runtime=0.153069
    X-UA-Compatible=IE=Edge,chrome=1
    BODY
    '{"errors":{"base":["Login or email required"]}}'

**Comment by Lordonnance** [comment]
I logged the facebook session object for the two cases.

First with the original Q-municate source code, facebook app and
credentials, then with a new Quickblox app (credentials changed in src /
... / utils / Consts.java) connected to a new facebook app.

Here are the traces and you can see that the permissions in both cases are
the same, public profile.

Anyway the first works and proceeds to the app when the second stops
receiving "email or login required" from Quickblox server...

File: BaseAuthActivity
Method: FacebookSessionStatusCallback

Q-MUNICATE
10-23 17:41:18.495: D/BOBBY AUTH(10773): BaseAuthActivity Facebook session
: {Session state:OPENED, token:{AccessToken token:ACCESS_TOKEN_REMOVED
permissions:[public_profile]}, appId:605405446247805}

NEW APP
10-23 17:35:17.395: D/BOBBY AUTH(10248): BaseAuthActivity Facebook session
: {Session state:OPENED, token:{AccessToken token:ACCESS_TOKEN_REMOVED
permissions:[public_profile]}, appId:544563002384402}

2015-10-23 19:36 GMT+02:00 dnyasae <notifications@github.com>:
