### ISSUE TITLE
Facebook setup

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-android#42]
I'm trying to make this application.
But I want to connect it to a new app on Facebook.
Can you explain how? where to set the ID?
Thanks I hope someone can help me

**Comment by Lordonnance** [comment]
You can update the facebook_id is in the xml files named "apikey.xml" in q_municate_app ressources
[Q-municate_app\src\main\res\values]

**Comment by turopEDSoft** [comment]
Thank you.
I have yet to create the facebook app so now I want to see if it works good chat.
Inside the XML file that you told me this is facebook_app_id which is the ID of the app of facebook is also push_registration_app_id this is the ID of google for notifications?
I can not find the fields for entering data of quikblox. where they are inserted?
Thank you in advance

**Comment by turopEDSoft** [comment]
I'm sorry, I found the file to insert the data.
One last thing.
Can you tell me how to implement the login via google?

**Comment by Lordonnance** [comment]
As far as I know Quickblox doesn't provide any method to sign in via Google
directly (only Facebook and Twitter for the time being)

One thing you could do is to handle Google SignIn yourself with email
permission then proceed to a standard email/pwd signup/in with Quickblox.

Hope it helped

On Friday, October 23, 2015, turopEDSoft <notifications@github.com> wrote:

> I'm sorry, I found the file to insert the data.
> One last thing.
> Can you tell me how to implement the login via google?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuickBlox/q-municate-android/issues/42#issuecomment-150654851>
> .
>


--

**Comment by turopEDSoft** [comment]
Thanks, I think I will do so.

I'm testing the application on two devices.
I created a key apy for gcm and added quickblox.

By sending a notification through the site all works.

You can view notifications for messages between users while the app is closed?

**Comment by Lordonnance** [comment]
Yes, for call and message

2015-10-23 22:43 GMT+02:00 turopEDSoft <notifications@github.com>:

**Comment by turopEDSoft** [comment]
For calls works is if the application is in the background if it is closed.
For notifications sent manually by quickblox always it works.
For regular messages from users not, what could be wrong?

**Comment by turopEDSoft** [comment]
I created and added the facebook app.

The problem is that when I go to cvliccare of calls through facebook I get a screen that says:

Game request are only avaiable to games.

What should I do?
