### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-android#46]
Hello to all. It is a great application I just finished to update the material design. Only problem not work chat notifications. if sending a notification from the site of quickblox notifications appear. also appear when you make a call but can not quite notifications for chat messages. you can help me solve?

**Comment by pr33t** [comment]
Hi @EminDemiri  I am not even able to receive notification from site. how you implemented this can you please help.

**Comment by rhadeed** [comment]
How to receive notification from the site?
