### ISSUE TITLE
App is connected login is working but i never found user and friend list in the app.

### ISSUE THREAD

**Issue by pr33t** [QuickBlox/q-municate-android#51]
Hi,

App is connected login is working but i never found user and friend list in the app.

How to use it please help me with this.

Thanks!

**Comment by DatzZDeVesh** [comment]
yes me too

**Comment by pr33t** [comment]
@DatzZDeVesh  Now its working for me. if you are using this app using your account details then you can go in contacts and search your friends by name and you will find the same in the list view.

**Comment by DatzZDeVesh** [comment]
ok THanks.PLease tell me one more thing that what are the charges for the video and audio calling!
Is it totally FREE by webrtc?

**Comment by Widiyanto** [comment]
me too, when use default  QB_APP_ID, QB_AUTH_KEY, QB_AUTH_SECRET in this project, finding user work fine, but when I change with my own app i never found user and friend list in the app, but actually i have four user in my admin panel.

**Comment by aceead** [comment]
Still not found other users
It is by name or email or phone?

**Comment by Widiyanto** [comment]
Problem solved sir, just check app setting "Allow to retrieve a list of users" in admin panel quickblox

**Comment by JuniorVouma** [comment]
when you edit the app, your friends have to sign up in your app using their emails and you can retrieve them only if their emails are saved in your contact.
