### ISSUE TITLE
Connection closed : No xmppconnection. Fail to retrieve settings from crashlytics

### ISSUE THREAD

**Issue by vinaytumbemane** [QuickBlox/q-municate-android#63]
I am unable to login to qmunicate app. I get following error. Internet connection is working.

![connection closed - no xmppconnection error](https://cloud.githubusercontent.com/assets/12265732/13701587/f752504c-e7ae-11e5-94a4-dca867e2e187.PNG)

`01-01 06:07:11.850    4253-4253/? E/MACAndIPAddress﹕ getMACAddress(String interfaceName)

01-01 06:07:11.870    4253-4253/? E/LandingActivity﹕ macAddress = 26:A1:B8:99:F0:0E
01-01 06:07:11.870    4253-4253/? E/LandingActivity﹕ macAddress = 26A1B899F00E
01-01 06:07:11.980    4253-4253/? E/sign up﹕ password_Text = apptester1
01-01 06:07:51.650    4253-4269/? E/Crashlytics﹕ Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.quickblox.flamingoxmpp/settings
01-01 06:07:51.810    4253-4270/? E/Crashlytics﹕ Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.quickblox.flamingoxmpp/settings
01-01 06:09:11.250    2371-4364/? E/GCoreUlr﹕ [ 01-01 06:09:11.290  2016: 2087 D/SyncManager ]
    failed sync operation flamingolite@gmail.com u0 (com.google), com.google.android.location.reporting, PERIODIC, earliestRunTime 1284260, SyncResult: stats [ numIoExceptions: 1]
01-01 06:11:54.540    2356-3755/? E/GTalkService﹕ connectionClosed: no XMPPConnection - That's strange!
01-01 06:15:49.000    1517-1996/? E/BandwidthController﹕ Updating quota globalAlert failed (No such file or directory)
01-01 06:17:34.730    2356-3755/? E/GTalkService﹕ connectionClosed: no XMPPConnection - That's strange!
`

Can any tell whats happening and how can I resolve it?

**Comment by pourya2374** [comment]
I have the same issue

**Comment by tatanka987** [comment]
Please provide steps to reproduce and full log. Additionally specify any changes which you do in project.
