### ISSUE TITLE
UserID in Object QbDialog = null

### ISSUE THREAD

**Issue by tuanhs66** [QuickBlox/q-municate-android#64]
Dear,
I want to add, delete User and edit information in Group-Dialog but in the field UserID(in Object Dialog QB) returns null. Can not know who is administrator ==> return message: "{"errors":["You don't have appropriate permissions to perform this operation"]}".

P / s: Please help me this problem.

Thanks!

**Comment by AntonDyach** [comment]
Hi, Tuanhs66 

Can you please specify Group dialog type ( http://quickblox.com/developers/Chat#Create_dialog) ? 
Please provide us logs with this logic (request/ response), so we can localize the issue. 

Thanks

**Comment by tuanhs66** [comment]
Dear,
When create Group dialog successfull and response:
{"_id":"56fba0b579ac1cae9f0009af","created_at":"2016-03-30T09:47:33Z","last_message":null,"last_message_date_sent":null,"last_message_user_id":null,"name":"Dang 55, Aas99999 Bbbjsjkss, Andlenovo","occupants_ids":[639,847,1142],"photo":null,"silent_ids":[],"type":2,"updated_at":"2016-03-30T09:47:33Z","user_id":847,"xmpp_room_jid":"3_56fba0b579ac1cae9f0009af@muc.chatqb.sembangchat.com","unread_messages_count":null}.
  But in curren Table "dialog"  not contain user_id Field(I think it is incorrect). When update info(ex: name Group dialog), it returns the message: {"errors":["You don't have appropriate permissions to perform this operation"]}
* Request update name Group dialog:
*********************************************************
 === REQUEST ==== 0602e791-0da1-4897-bc9b-a691bbdbe77c ===
                                                         REQUEST
                                                             PUT https://apiqb.sembangchat.com/chat/Dialog/56fba0b579ac1cae9f0009af.json
                                                         HEADERS
                                                             QuickBlox-REST-API-Version=0.1.1
                                                             QB-SDK=Android 2.5.1
                                                             QB-Token=eec40885cb984431a095adb87f66aca1c5d55fba
                                                         PARAMETERS
                                                             name=Dang 55, Aas99999 Bbbjsjkss, Andlenovo
                                                             push[name][]=Dang 55, Aas99999 Bb
                                                         INLINE
                                                             PUT https://apiqb.sembangchat.com/chat/Dialog/56fba0b579ac1cae9f0009af.json?name=Dang+55%2C+Aas99999+Bbbjsjkss%2C+Andlenovo&push[name][]=Dang+55%2C+Aas99999+Bb
*********************************************************
* And Response:
 *********************************************************
                                                         *** RESPONSE *** 0602e791-0da1-4897-bc9b-a691bbdbe77c ***
                                                         STATUS : 403 
                                                         HEADERS
                                                             QuickBlox-REST-API-Version=0.1.1
                                                             X-Runtime=0.022501
                                                             Content-Length=79
                                                             X-UA-Compatible=IE=Edge,chrome=1
                                                             X-Request-Id=dd2dc56380797cc514e0a1d900c13b77
                                                             X-Rack-Cache=invalidate, pass
                                                             Connection=Close
                                                             X-Android-Response-Source=NETWORK 403
                                                             Server=nginx/1.8.1
                                                             QB-Token-ExpirationDate=2016-03-30 11:57:57 +0000
                                                             Cache-Control=no-cache
                                                             Status=403 Forbidden
                                                             X-Android-Selected-Transport=http/1.1
                                                             Date=Wed, 30 Mar 2016 09:58:03 GMT
                                                             Access-Control-Allow-Origin=*
                                                             X-Android-Received-Millis=1459331883168
                                                             Content-Type=application/json; charset=utf-8
                                                             X-Android-Sent-Millis=1459331882754
                                                         BODY
                                                             '{"errors":["You don't have appropriate permissions to perform this operation"]}'
 *********************************************************
P / s: Please help me this problem.
Thanks!

**Comment by AntonDyach** [comment]
Hi, 

Please do following to update dialog name:
- Set new name for "old" (existing) dialog 
- update dialog  (http://quickblox.com/developers/Android_XMPP_Chat_Sample#Update_group_dialog)

Find bellow the code: 
 oldDialog.setName("newName");
QBGroupChatManager groupChatManager = QBChatService.getInstance().getGroupChatManager();
QBDialog updatedDialog = groupChatManager.updateDialog(oldDialog, null);

Please try this and let us know, if this is useful.
