### ISSUE TITLE
Push Notification Not received

### ISSUE THREAD

**Issue by vinaytumbemane** [QuickBlox/q-municate-android#65]
I am not getting the push notification after changing the package name.?
Can anyone suggest what should be done to get push notification?

Should I add new api key? 
Any one from quickblox know about this? please guide me.

Thank you.

**Comment by tatanka987** [comment]
Hi vinaytumbemane, what additional changes did you have in your project except the package name?

**Comment by BhuvneshK9** [comment]
Hello,

I am also not getting push notification after configuring this project.
Please suggest if anyone configure this project successfully.

Thanks,

**Comment by tatanka987** [comment]
Hello BhuvneshK9, write what exactly changes did you do in your project

**Comment by adinorteylawerteh** [comment]
Same here push notifications are not working... show as sent in the dashboard

**Comment by FelipeMiranda** [comment]
After updating to version 2.5 push notification stopped to work.

**Comment by RomanPronin** [comment]
Hi, @FelipeMiranda, can you explain in more details your problem. You do not receive pushes on all devices or just on some? Did you make any changes in project?
