### ISSUE TITLE
How to listener Update message in Quickblox 2.5.1

### ISSUE THREAD

**Issue by nguyenkhiem7789** [QuickBlox/q-municate-android#66]
Hi, my friends
I use quickblox 2.5.1 for android develop.
But I don't know How to can listener update message status : read and delivered ?
I think use interface QBMessageListener but in version 2.5.1 method "processMessageDelivered" and "processMessageRead" is removed
sorry because my english is not good

**Comment by tatanka987** [comment]
Hi

**Comment by tatanka987** [comment]
Hi, please see our documentation by link http://quickblox.com/developers/Android_XMPP_Chat_Sample#Delivered_status

**Comment by nguyenkhiem7789** [comment]
Thanks, But now I have problem with display online/offline off user. I read
link http://quickblox.com/developers/Android_XMPP_Chat_Sample#Contact_list
and I try use QBRosterListener to listener update status online or offline.
Because I use Q-municate-core implement to my project, so I think
QBRosterListener will
auto listener action online/offline.
But It don't happen. Can you tell me How can I use QBRosterListener in my
project

2016-03-29 17:37 GMT+07:00 tatanka987 <notifications@github.com>:
