### ISSUE TITLE
Error: cannot find symbol variable APP_ID Android Studio

### ISSUE THREAD

**Issue by genidoxapps** [QuickBlox/q-municate-android#70]
Tried to build in android studio and it's giving me this error, I have been trying to fix it for days, can't find anything online, I would appreciate any help

Error:(8, 27) error: cannot find symbol variable APP_ID
Error:(12, 27) error: cannot find symbol variable AUTH_KEY
Error:(16, 27) error: cannot find symbol variable AUTH_SECRET
Error:(28, 27) error: cannot find symbol variable PUSH_REGISTRATION_APP_ID
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Error:Execution failed for task ':Q-municate_app:compileReleaseJavaWithJavac'.

> Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED
> Information:Total time: 16.563 secs
> Information:5 errors
> Information:0 warnings
> Information:See complete output in console

See screenshot for more info:

![untitled](https://cloud.githubusercontent.com/assets/14912672/14483675/45bec16c-00fe-11e6-8728-c8a9c3769593.png)

**Comment by eduardobona** [comment]
We are happy to offer you a chat application out of the box. You can customize this application to on your needs (with attribution as stated in the license). QuickBlox is used for the backend http://quickblox.com. Find more information about Q-municate Android in our Developers section

http://quickblox.com/developers/Q-municate#Q-municate_Android
