### ISSUE TITLE
Not able to send Push Notification explicitly

### ISSUE THREAD

**Issue by ayushishah-easternts** [QuickBlox/q-municate-android#71]
D/QBASDK: *********************************************************
                                                                  **\* RESPONSE **\* 37efaf24-ba45-4dad-97db-f00f84ad7d94 ***
                                                                  STATUS : 422 
                                                                  HEADERS
                                                                      X-Runtime=0.304270
                                                                      Cache-Control=no-cache
                                                                      X-Rack-Cache=invalidate, pass
                                                                      QuickBlox-REST-API-Version=0.1.1
                                                                      X-UA-Compatible=IE=Edge,chrome=1
                                                                      QB-Token-ExpirationDate=2016-04-13 09:51:17 UTC
                                                                      Status=422 Unprocessable Entity
                                                                      X-Request-Id=261f8657eed00fe9e5423d3ea42f77e9
                                                                      X-Android-Response-Source=NETWORK 422
                                                                      Connection=Close
                                                                      X-Android-Sent-Millis=1460533934291
                                                                      Content-Type=application/json; charset=utf-8
                                                                      Date=Wed, 13 Apr 2016 07:52:16 GMT
                                                                      Server=nginx/1.8.1
                                                                      Content-Length=45
                                                                      X-Android-Received-Millis=1460533936523
                                                                      Access-Control-Allow-Origin=*
                                                                  BODY
                                                                      '{"errors":["No one can receive the message"]}'

**Comment by tatanka987** [comment]
please check subscriptions in QuickBlox admin panel for your users
