### ISSUE TITLE
can not add member to group - You don't have appropriate permissions to perform this operation

### ISSUE THREAD

**Issue by estysherman** [QuickBlox/q-municate-android#72]
in adding member to group in quickblox android i get: You don't have appropriate permissions to perform this operation.
### private boolean UpdateDialogGroupQBUsers(int userId) {

QBRequestUpdateBuilder requestBuilder = new QBRequestUpdateBuilder();
requestBuilder.push("occupants_ids", userId); // add another users
QBChatService.getInstance().getGroupChatManager().updateDialog(QBDialog, requestBuilder, new QBEntityCallback() {
@Override
public void onSuccess(QBDialog dialog, Bundle args) {
Log.d("addMember", "success");
isSuccess = true;
}
@Override
public void onError(QBResponseException e) {
Log.d("addMember",e.toString());
isSuccess = false;
}
});
return isSuccess;
}
}

**Comment by tatanka987** [comment]
please, see documentation by link http://quickblox.com/developers/Chat#Update_dialog
