### ISSUE TITLE
Could not find property 'prodPushRegistrationAppID'

### ISSUE THREAD

**Issue by ulamnet** [QuickBlox/q-municate-android#73]
Hello , ı create gradle.properties file and import creditantials but ı still get this error ;

Error:(44, 0) Could not find property 'prodPushRegistrationAppID' on project ':Q-municate_app'.
<a href="openFile:C:\Users\oem\Desktop\q-municate-android-master\Q-municate_app\build.gradle">Open File</a>

How to fix this error ?

Thanks.

**Comment by tatanka987** [comment]
hello, please check the name of prodPushRegistrationAppID in your gradle.properties file

**Comment by ulamnet** [comment]
![prod](https://cloud.githubusercontent.com/assets/583003/14716438/b19fb596-07f5-11e6-96aa-99a55df3fed3.PNG)

this ?

**Comment by tatanka987** [comment]
yes, you have prodPushRegistra**r**ionAppID, but correct prodPushRegistra**t**ionAppID

**Comment by ulamnet** [comment]
now ı get this error ; Error:Configuration with name 'default' not found.

**Comment by tatanka987** [comment]
you need to select build variant **debug** if you did'n change file build.gradle in  Q-municate_app  module

**Comment by ulamnet** [comment]
ı don't change anything.sorry my bad english :)

**Comment by ulamnet** [comment]
but ı don't see debug module .

**Comment by ulamnet** [comment]
Sorry for closed, But ı don't see debug module

**Comment by tatanka987** [comment]
please, follow our [instruction](http://quickblox.com/developers/Q-municate#Q-municate_Android) step by step for to run Q-municate Android
