### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Alrami7** [QuickBlox/q-municate-android#76]
Hi everyone,
I need agree location module to my app but I can't do it.
Anyone can tell me how I can do it?

Thanks.
Greetings.

**Comment by Alrami7** [comment]
I solved the problem!

**Comment by JuniorVouma** [comment]
@Alrami7 can you tell me how did you do it?

**Comment by Alrami7** [comment]
Hi @JuniorVouma 

I create a service location and in onLocationChanged method , I call:
QBLocation location = new QBLocation(lat, lng); and then
QBLocations.createLocation(location, new QBEntityCallback<QBLocation>()

I hope this solve your problem.
