### ISSUE TITLE
There is not exist delete friend option

### ISSUE THREAD

**Issue by YongfuZhuang** [QuickBlox/q-municate-android#8]
I tried to add to user by the search.

But i can't remove one from the contract.

If possible, please kindly let me know.

Thanks

**Comment by migueltarga** [comment]
[Right here](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_app/src/main/java/com/quickblox/q_municate/ui/friends/FriendDetailsActivity.java#L195)
