### ISSUE TITLE
Error when build to Android studio

### ISSUE THREAD

**Issue by nguyenkhiem7789** [QuickBlox/q-municate-android#81]
When I download q-municate-android-master 2.0 and build to android studio, have a issues : 

Error:(41, 0) Could not find property 'prodAppID' on project ':Q-municate_app'.
<a href="openFile:D:\Android\Chat\Qmunicate 2.0\q-municate-android-master\Q-municate_app\build.gradle">Open File</a>

How to can I fix it ?

**Comment by tatanka987** [comment]
please, see our documentation for running Q-municate app by link http://quickblox.com/developers/Q-municate#Q-municate_Android

**Comment by JuniorVouma** [comment]
the easy fix is to create a new android studio project, then copy the properties(gradle.properties) file in your Q-municate folder, edit the file as followed:
#QB credentials
prodAppID=\"00000\"
prodAuthKey=\"xxxxxxxxxxxx\"
prodAuthSecret=\"xxxxxxxxxxxx\"
prodFacebookAppID=\"xxxxxxxxxxxxx\"
prodPushRegistrationAppID=\"xxxxxxxxxxxxx\"

replace the "xxxxxx" by your infos.

**Comment by ckibuchi** [comment]
@JuniorVouma , Sir! I did the above on my app but my friend requests goes to q-municate not my app.
But the users created are available on quickblox account of the app.
Help out pliz

**Comment by JuniorVouma** [comment]
@ckibuchi hi! you've to go to your quickblox app then settings "allow to retrieve all users" then all you need to do is to search by name in the search button.     for the friend request, go to quicblox, users, settings then set the path as written in that section.

**Comment by MinZan** [comment]
@tatanka987 
I did follow exactly from the  http://quickblox.com/developers/Q-municate#Q-municate_Android but 
still this issue can't solve it yet. I think most of the developer have all same issues.
Please provide more specific answer for this issues. Thanks
