### ISSUE TITLE
Translation in italian language

### ISSUE THREAD

**Issue by matteoraggi** [QuickBlox/q-municate-android#82]
What about the possibility to translate the interface? I would need to translate in in italian.

**Comment by tatanka987** [comment]
hi, for translating Q-municate's interface you need translate next string resources: 
/q-municate-android/Q-municate_core/src/main/res/values/strings.xml
/q-municate-android/Q-municate_app/src/main/res/values/strings.xml

or
you can create multilanguage application, see Google's documentation for it by link https://developer.android.com/training/basics/supporting-devices/languages.html
