### ISSUE TITLE
notifications problem

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-android#83]
Hello everyone, it really like this new version, solves many problems of the previous year.

The only flaw is that now the application does not register more users to notifications.

When a user registers via the application that is not registered to receive notifications from quickblox site.

What can I do to fix?

**Comment by RomanPronin** [comment]
Hi, could you clarify your problem? What's notification do you mean?

**Comment by EminDemiri** [comment]
in practice they are not registered users to receive notifications in the background.
Anceh if register 10 new accounts from the dashboard QB do not see any user subscribed for notifications

**Comment by RomanPronin** [comment]
You can check logs for the presence of successful subscription on push notification, and maybe you'll find some errors about it. Also check  Google Cloud Messaging (GCM) API key "Environment: production" in your admin panel, cause on default Q-municate environment set on production.
