### ISSUE TITLE
Friend requests go to the main q-municate app

### ISSUE THREAD

**Issue by ckibuchi** [QuickBlox/q-municate-android#86]
I have created  gradle.properties
Added:
prodAppID=\"00000\"
prodAuthKey=\"xxxxxxxxxxxx\"
prodAuthSecret=\"xxxxxxxxxxxx\" 
prodFacebookAppID=\"xxxxxxxxxxxxx\" 
Note: I have repaced the xxx with the actual values from my app on quickblox.
However, friend requests sent from my app go to q-municate app instead of mine.
When someone installs q-municate from playstore, they get requests that were sent from my app

**Comment by JuniorVouma** [comment]
@ckibuchi your app still linked to q-municate, edit it in the code or go in quickblox, users, settings then set your path and descriptions

**Comment by ckibuchi** [comment]
@JuniorVouma ,
Where do I edit that in the code please?
coz my gradle.properties file already has prodAppID,prodAuthKey,prodFacebookAppID,prodFacebookAppID,set as what is on quickblox.
"...set your path and descriptions" which path? Kindly help me out. Thanks

**Comment by JuniorVouma** [comment]
@ckibuchi your problem is the fact that you can't find your friends or when you invite someone it link the mail to q-municate and its website?

**Comment by JuniorVouma** [comment]
@ckibuchi when you go to quiblox.com and signin, on the bottom right there is users click on it, once it's open on top right there is settings, click on it and it'll show you some tags you can use to correct the invite friends lines. 
for requesting the friends on your app signin in quickblox.com click on app then settings and allow retrieve all users.
