### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by KungFuArsong** [QuickBlox/q-municate-android#90]
There is no the function that remove one chat item.

**Comment by tatanka987** [comment]
for remove any chat from dialogs list need make long click on selected dialog and select "Delete dialog"

**Comment by KungFuArsong** [comment]
not delete dialog
I mean the one chat item.
If I chatted "Hi", I hope to remove the chat from the list
like skype.

**Comment by JuniorVouma** [comment]
@KungFuArsong you are right that feature is not included

**Comment by KungFuArsong** [comment]
there is deleteMessage() function
but It's not working well.
