### ISSUE TITLE
Unable to receiving incoming calls when app is closed

### ISSUE THREAD

**Issue by CRUDTechnolgoy** [QuickBlox/q-municate-android#93]
Hi everything is working fine & supab. new version is awsome. but one issue is there i am not able to receive call when my app is closed. it's working fine when app is open or in forground state. but when app is killed the CallActivity is not invoking..

**Comment by samsadch** [comment]
Anybody here can give me any issue fix?

**Comment by RomanPronin** [comment]
In current Q-mun version 2.7, background calls work.
