### ISSUE TITLE
Group Audio call and Video Call

### ISSUE THREAD

**Issue by jaikikani** [QuickBlox/q-municate-android#96]
How to add group audio call and group video call in existing project when used previous library? I have try but issue is that  library is conflict.

**Comment by tatanka987** [comment]
in new Q-municate release we plan to update QuickBlox Android SDK to version 2.6.1 after that you will can add group audio call and group video call functionality to your existing project

**Comment by rohitrathore** [comment]
please  provide information about group video call and audio ...
because i  have try  but  get some issue
