### ISSUE TITLE
QBMessageUpdateBuilder not found

### ISSUE THREAD

**Issue by CRUDTechnolgoy** [QuickBlox/q-municate-android#98]
QBMessageUpdateBuilder messageUpdateBuilder = new QBMessageUpdateBuilder();
                messageUpdateBuilder.updateText(newBody) //updates message's text
                        .markDelivered() //mark message as delivered on server
                        .markRead(); //mark message as read on server

QBChatService.updateMessage(messageId, dialogId, messageUpdateBuilder, new QBEntityCallback<Void>()
    @Override
    public void onSuccess(Void result, Bundle params) {

```
}

@Override
public void onError(QBResponseException errors) {

}
```

this code is not working

**Comment by RomanPronin** [comment]
Hi, provide us more info about what is not working in your code with QBChatService.updateMessage, give us steps, logs.

**Comment by CRUDTechnolgoy** [comment]
hi @RomanPronin  it's working now. perfect but one problem is i don't have any method or any listener to listen changes at receiver side. how i identity at receiver side this messages is changed.  r8t now i have to fetch every time data from server.

**Comment by RomanPronin** [comment]
We don't have listeners about updating message, but you can use system message to send notification to other users about this event http://quickblox.com/developers/Android_XMPP_Chat_Sample#System_notifications

**Comment by RomanPronin** [comment]
Long time inactivity.
