### ISSUE TITLE
Twitter Digits wrong example code / not working

### ISSUE THREAD

**Issue by moritzm** [QuickBlox/q-municate-android#99]
I am trying to get Twitter Digits login working. The login via Twitter Digits is working so far, but i can not login to Quickblox, because the documentation in https://quickblox.com/developers/SimpleSample-users-android#Signing_In_with_Twitter_Digits is using not existing code. It uses the method `QBUsers.signInUsingTwitterDigits()` which does not exist in the class `QBUsers`.
I am using the Q-Municate source code https://github.com/QuickBlox/q-municate-android.

Does anyone have the same issue? Or have a solution for me?

**Comment by moritzm** [comment]
I found out, that the app is using an old version of the sdk `quickblox-android-sdkcore-2.4.jar`. The QuickBlox Android SDK has the newer version 2.6.1. So i need to update the sdk in the app somehow.

**Comment by tatanka987** [comment]
hello @moritzm, in new Q-municate release we plan to update QuickBlox Android SDK to version 2.6.1 and add  Twitter Digits login functionality
